### ISSUE TITLE
One requirements file per task

### ISSUE THREAD

**Issue by ethanwharris** [PyTorchLightning/lightning-flash#1001]
Users shouldn't have to install requirements they aren't using. Should make the following changes:
- one requirements file per task
- allow the `requires` decorator to reference a requirements file (i.e. remove current manual approach)

**Comment by abhijithneilabraham** [comment]
Hi @ethanwharris , do you mean, the installation should be something like the following?

pip install 'lightning-flash[task]' 

Isn't this already implemented within Flash? I saw an error output recommending something like this. Maybe what you're seeking is an improvement to the approach taken for the above?
