### ISSUE TITLE
[RFC] Deprecate `model.predict` in favour of `Trainer.predict`

### ISSUE THREAD

**Issue by ethanwharris** [PyTorchLightning/lightning-flash#1004]
`model.predict` has a lot of usability issues:
- not clear how to load from different inputs
- no way to pass additional data loading arguments
- no docstring specific to the particular task
- lots of magic in the background to resolve e.g. transforms and stuff like that
- not able to handle much load (see #983)
- two ways to do prediction

We should deprecate in favour of using a datamodule and Trainer. E.g. image classification prediction is currently:
```
predictions = model.predict(
    [
        "data/hymenoptera_data/val/bees/65038344_52a45d090d.jpg",
        "data/hymenoptera_data/val/bees/590318879_68cf112861.jpg",
        "data/hymenoptera_data/val/ants/540543309_ddbb193ee5.jpg",
    ]
)
```

Would become:
```
predict_data_module = ImageClassificationData.from_files(predict_files=[
    "data/hymenoptera_data/val/bees/65038344_52a45d090d.jpg",
    "data/hymenoptera_data/val/bees/590318879_68cf112861.jpg",
    "data/hymenoptera_data/val/ants/540543309_ddbb193ee5.jpg",
])
predictions = trainer.predict(model, datamodule=predict_data_module)
```

**Comment by tchaton** [comment]
I believe the `model.predict` is confusing as users don't have fine control over the data being processed.

I would prefer relying on `trainer.predict` which is the default recommended way with PyTorch Lightning.

**Comment by Borda** [comment]
I would tent to string input to Dataset (maybe DataLoader) only and then it is up to the user to load data within...

Positive:
- user can easier manage what the input data does
- we provide basic tooling so it shall be at most one more line of code
- simple and clean adding extra arguments

Negative:
- one more line of code and it loses some kind of magic (also the magic is the source of confusion)
- we need to well document and see dataset compatibility and list all available dataset
