### ISSUE TITLE
Remove kornia version limitation

### ISSUE THREAD

**Issue by twsl** [PyTorchLightning/lightning-flash#1006]
## 🐛 Bug

Remove the version limit for kornia in the extra image dependencies.
If currently limits kornia to a version that is a couple month old.
Check, if the dependency can be removed all together.

https://github.com/PyTorchLightning/lightning-flash/blob/master/requirements/datatype_image.txt#L5

### To Reproduce

1. Install kornia==0.6.1
2. Try to install lightning-flash[image]

### Environment

 - PyTorch Version (e.g., 1.0): 1.10
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): -
 - Python version: 3.8
 - CUDA/cuDNN version: 11.5/8
 - GPU models and configuration:
 - Any other relevant information:

**Comment by twsl** [comment]
With the upcoming release for kornia, I'd like to bring it back on the agenda. Maybe I can find some time soon

**Comment by ethanwharris** [comment]
Hey @twsl I forgot to come back to this, but we recently removed a lot of out kornia usage so I think it may now be possible to remove the limitation, which I'm trying here: #1147
