### ISSUE TITLE
audio classification example doesn't run with the recent code change

### ISSUE THREAD

**Issue by mrleu** [PyTorchLightning/lightning-flash#1048]
## 🐛 Bug

So i realized the recent changes on https://github.com/PyTorchLightning/lightning-flash/blob/master/flash_examples/audio_classification.py is breaking the flash example with the current flash version installed via pip: version `lightning-flash==0.5.2`

### To Reproduce

1. run `python3 audio_classifiction.py`
2. get error: `TypeError: __init__() got an unexpected keyword argument 'transform_kwargs'
3. once i've updated from `transform_kwargs=dict(spectrogram_size=(64, 64)),` to `spectrogram_size=(64, 64)`, i get the error `MisconfigurationException: strategy should be a ``pytorch_lightning.callbacks.BaseFinetuning``callback or a str within ['no_freeze', 'freeze', 'freeze_unfreeze', 'unfreeze_milestones']`
4. after fixing `https://github.com/PyTorchLightning/lightning-flash/blob/master/flash_examples/audio_classification.py#L36` to only have `freeze_unfreeze` as string, then the script runs.

![image](https://user-images.githubusercontent.com/40532483/145527569-114ac500-d450-4d62-b237-58f78b3cc7d3.png)

### Environment

 - PyTorch Version (e.g., 1.0): torch==1.10.0
 - OS (e.g., Linux): linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: python 3.9
 - CUDA/cuDNN version: 
 - GPU models and configuration:
 - Any other relevant information:

### Additional context

I was hoping to run audio classification to make sure my machine can run the model for next week's community sprint. Happy to create a PR if this is indeed a bug.

**Comment by karthikrangasai** [comment]
Hello @mrleu,

In case you want to use the `freeze_unfreeze` strategy, it's should be input as a Tuple : `("freeze_unfreeze", 1)` or any epoch number of your choice that is less than the total number of epochs.

`no_freeze` and `freeze` are the only strategies that can be passed as just strings.

Checkout the documentation [here](https://lightning-flash.readthedocs.io/en/latest/general/finetuning.html)

**Comment by mrleu** [comment]
ah i see. good to know that only `no_freeze` and `freeze` are the only strategies that can be passed a strings. 

But let me clarify the bug i'm seeing: when i entered tuples: `("freeze_unfreeze", 1)` as the argument, i get the error message: `MisconfigurationException: strategy should be a ``pytorch_lightning.callbacks.BaseFinetuning``callback or a str within ['no_freeze', 'freeze', 'freeze_unfreeze', 'unfreeze_milestones']`

See screenshot here:
![image](https://user-images.githubusercontent.com/40532483/145535850-b7fca982-07f8-4e56-ac7b-471d12c44d3f.png)

**Comment by ethanwharris** [comment]
Closing this as it is working for me on Flash master. @mrleu please feel free to re-open if you have any further questions :smiley:
