### ISSUE TITLE
[ImageEmbedder] BASE_MODEL_NAME attribute missing in DINO and MOCO configs

### ISSUE THREAD

**Issue by francescorubbo** [PyTorchLightning/lightning-flash#1068]
## 🐛 Bug

ImageEmbedder training fails for DINO and MOCO architectures with error
```
  File "/root/.venv/lib/python3.8/site-packages/vissl/models/__init__.py", line 69, in build_model
    model_name = model_config.BASE_MODEL_NAME
  File "/root/.venv/lib/python3.8/site-packages/vissl/config/attr_dict.py", line 49, in __getattr__
    raise AttributeError(
AttributeError: AttrDict object has no attribute BASE_MODEL_NAME.
```

### To Reproduce

Follow the example from the docs using DINO or MOCO
https://lightning-flash.readthedocs.io/en/stable/reference/image_embedder.html

#### Code sample

```
datamodule = ImageClassificationData.from_datasets(
    train_dataset=CIFAR10(".", download=True),
    batch_size=16,
)
embedder = ImageEmbedder(
    backbone="vision_transformer",
    training_strategy="dino",
    head="dino",
    pretraining_transform="dino_transform",
)
trainer = flash.Trainer(max_epochs=3, gpus=1, strategy="ddp")
trainer.fit(embedder, datamodule=datamodule)
```

### Expected behavior

The VISSL adapter (https://github.com/PyTorchLightning/lightning-flash/blob/master/flash/image/embedding/vissl/adapter.py#L126-L155) should include in the model configuration the attribute `BASE_MODEL_NAME` that is used here https://github.com/facebookresearch/vissl/blob/main/vissl/models/__init__.py#L69

### Environment

 - PyTorch Version (e.g., 1.0): 1.10.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): `pip`
 - Python version: 3.8
 - CUDA/cuDNN version: CUDA 11.3
 - GPU models and configuration: A100 (Google Cloud `a2-highgpu-1g`)
 - Any other relevant information: 
     - pytorch-lightning==1.5.5
     - lightning-bolts==0.4.0
     - lightning-flash[image]==0.5.2
     - vissl==0.1.6

### Additional context

Hard-coding `config["BASE_MODEL_NAME"] = "multi_input_output_model"` enables training without errors.

**Comment by DLX1234** [comment]
> 

Cuold you please tell me where to hard-coding? I recently met this error, too.
Thanks

**Comment by francescorubbo** [comment]
@DLX1234 you would want to add `"BASE_MODEL_NAME": "multi_input_output_model",` to the config right before L129 in https://github.com/PyTorchLightning/lightning-flash/blob/master/flash/image/embedding/vissl/adapter.py#L126-L155.

It should look like this::
```
    def get_model_config_template():
        cfg = AttrDict(
            {
                "BASE_MODEL_NAME": "multi_input_output_model",
                "SINGLE_PASS_EVERY_CROP": False,
                "INPUT_TYPE": "rgb",
                "MULTI_INPUT_HEAD_MAPPING": [],
                "TRUNK": AttrDict({}),
                "HEAD": AttrDict(
                ...
```

**Comment by DLX1234** [comment]
> "BASE_MODEL_NAME": "multi_input_output_model",

yeah, that solves the error !
Thank you very much

**Comment by krshrimali** [comment]
Fixed in https://github.com/PyTorchLightning/lightning-flash/pull/1196. Thanks for raising the issue.
