### ISSUE TITLE
ObjectDetectionData doc typos

### ISSUE THREAD

**Issue by ethanwharris** [PyTorchLightning/lightning-flash#1070]
## 📚 Documentation

In the API doc for ObjectDetectionData, the parameter descriptions for `train_ann_file` for `from_voc` and `from_via` both mention “COCO format”.

**Comment by MikeTrizna** [comment]
Hi @ethanwharris, I fixed the mentions to COCO format, but then also did a bit of entertaining digging to find references to the VIA and VOC formats. Check out the PR: https://github.com/PyTorchLightning/lightning-flash/pull/1073.
