### ISSUE TITLE
[Instance Segmentaion]  Cannot import name 'MasksRecordComponent' from 'icevision.core.record_components'

### ISSUE THREAD

**Issue by samyak1999** [PyTorchLightning/lightning-flash#1071]
### To Reproduce
Follow this link which redirects to the example in the doc [Instance Segmentaion](https://lightning-flash.readthedocs.io/en/latest/reference/instance_segmentation.html#flash-zero)

1. Import the libraries 
2. Run 
4.  Import error occurs

![image](https://user-images.githubusercontent.com/43057462/145973011-ceeb9a03-b74e-4135-8db2-b342e1d2b354.png)

#### Code sample
`from flash.image import InstanceSegmentation, InstanceSegmentationData`  
Error occurs while executing the above code.

### Expected behavior
Still not clear of the potential output. 

### Environment

-PyTorch Version (e.g., 1.0): 1.10.0
-OS (e.g., Linux): Windows
-How you installed PyTorch (conda, pip, source): pip
-Python version: 3.9
-CUDA/cuDNN version:  Non
-GPU models and configuration: Geforce 640M
-Any other relevant information:
        * pytorch-lightning==1.5.5
        * lightning-bolts==0.4.0
        * lightning-flash[image]==0.5.2

**Comment by ethanwharris** [comment]
Closing this as it should be fixed in Flash master. Please feel free to re-open if you still get the error :smiley:
