### ISSUE TITLE
Explanation of the InputTransform

### ISSUE THREAD

**Issue by bartonp2** [PyTorchLightning/lightning-flash#1081]
## ❓ Questions and Help

Is there an explanation of the `InputTransform` and how to use it anywhere?

I see that there are some basic examples under the documentation of some of the tasks. However, what I am missing is:
1. An explanation of what the `*_on_device()` functions refer to in contrast to the standard functions
2. How the various functions are combined? Many available functions overlap such as `per_sample_transform()`, `input_per_sample_transform()` and `train_input_per_sample_transform()`. Is simply the more specific function used or will the `per_sample_transform()`  always be applied first before applying the more specific functions?

**Comment by tchaton** [comment]
Hey @bartonp2,

Thanks for asking about the InputTransform. We just refactored Flash and the documentation will be updated in January.

Find the example here

**Comment by tchaton** [comment]
https://github.com/PyTorchLightning/lightning-flash/blob/master/flash_examples/flash_components/custom_data_loading.py

**Comment by tchaton** [comment]
https://github.com/PyTorchLightning/lightning-flash/blob/master/flash_examples/flash_components/custom_data_loading.py

**Comment by tchaton** [comment]
By default, the data in Flash are dictionarry. By using input_*, this would apply your function on the input key. And *_on_device is applied when the data are already on the gpus, tpu, etc...
