### ISSUE TITLE
Can't add augmentation to speech recognition.

### ISSUE THREAD

**Issue by dayvagrant** [PyTorchLightning/lightning-flash#1082]
#### What have you tried?
Looked at [this](https://github.com/PyTorchLightning/lightning-flash/issues/724) example but it didn't work.
Show an example of working code for adding augmentation in transform.

#### What's your environment?

 - lightning-flash==0.6.0

**Comment by dayvagrant** [comment]
My example for augmentation.
`
from flash.core.data.io.input_transform import InputTransform
from dataclasses import dataclass

@dataclass
class BaseSpeechInputTransform(InputTransform):

    # custom transforms.
    augmentation = Compose([
        Resampler(resample_rate=16000),
        PreEmphasisFilter(),
        AddGaussianNoise(min_amplitude=0.001, max_amplitude=0.02, p=0.3),
        Mp3Compression(backend="pydub", p=0.3),
            ])
    

    def sample_augmentator(self, sample, resample_rate=16000):
        sampling_rate = sample['metadata']['sampling_rate']
        sample['input'] = self.augmentation(sample['input'], sampling_rate)
        sample['metadata']['sampling_rate'] = resample_rate
        return sample

    def per_sample_transform(self):
        return self.sample_augmentator

`

**Comment by ethanwharris** [comment]
Nice! @dayvagrant this is awesome!!! Would you be interested in opening a PR to add this example to our speech recognition docs? We went through a refactor recently which is why the old example doesn't work. Would be very interested to hear your thoughts on the new API if there's anything you'd like to share :smiley:
