### ISSUE TITLE
Unable to load Image classification model in version 0.6.0

### ISSUE THREAD

**Issue by satishjasthisync** [PyTorchLightning/lightning-flash#1083]
## 🐛 Bug

The current 0.6.0 is not able to load a fine tuned model file from local path

This is the link to the model file:  https://syncortex-my.sharepoint.com/:u:/p/satish_jasthi/ET3rE5L3KZRDkCz12i-g5qkBgRFPFNm1yUXwdgmip9Snlg?e=wuKKaq

1. Download the model file
2. install lightning-flash==0.6.0 and  lightning-flash[image]
3. run this code
`from flash.image import ImageClassifier
model =  ImageClassifier.load_from_checkpoint('path_to_folder/pageClassifier_efficientnet_b0.pt')       
`
The error Im getting is
`Traceback (most recent call last):
  File "/home/user/project/project/module/moduleServe.py", line 5, in <module>
    model =  ImageClassifier.load_from_checkpoint(moduleModelCheckpointDir/'finetuned_efficientnet_b0.pt')       
  File "/home/user/anaconda3/envs/docLytAnlys/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 134, in load_from_checkpoint
    checkpoint = pl_load(checkpoint_path, map_location=lambda storage, loc: storage)
  File "/home/user/anaconda3/envs/docLytAnlys/lib/python3.8/site-packages/pytorch_lightning/utilities/cloud_io.py", line 38, in load
    return torch.load(f, map_location=map_location)
  File "/home/user/anaconda3/envs/docLytAnlys/lib/python3.8/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/user/anaconda3/envs/docLytAnlys/lib/python3.8/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/home/user/anaconda3/envs/docLytAnlys/lib/python3.8/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'ImageClassificationDataFrameDataSource' on <module 'flash.image.classification.data' from '/home/user/anaconda3/envs/docLytAnlys/lib/python3.8/site-packages/flash/image/classification/data.py'>`

OS Info:
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

Cuda info:  CUDA Version: 11.2  
### Environment

 - PyTorch Version:1.10.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8.12
 - CUDA/cuDNN version: 11.2
 - GPU models and configuration:
 - Any other relevant information:

This same code is working in 0.5.2 version of lightning flash but not working in 0.6.0

**Comment by ethanwharris** [comment]
Hey @satishjasthisync, thanks for reporting this, unfortunately it's not possible for us to make checkpoints cross-compatible with different versions of Flash so you would have to load the model with the same version of Flash that saved the checkpoint. Closing this as there is nothing we can do, but please feel free to re-open if you have any ideas about how the experience could be improved or want to discuss it further :smiley:
