### ISSUE TITLE
Wav2Vec by lightning flash on longer audio files

### ISSUE THREAD

**Issue by imavijit** [PyTorchLightning/lightning-flash#1087]
Hello,
I am trying to use fine-tuned wav2vec model by the lightning flash on longer audio file. (Files are mostly 2-3 hours long). I tried to use librosa stream. But I think the function I am using and tokenizer is not compatible.

#### Code
import torch
  
  import flash
  from flash.audio import SpeechRecognition, SpeechRecognitionData
  from flash.core.data.utils import download_data
  
  #####1. Create the DataModule
  download_data("https://pl-flash-data.s3.amazonaws.com/timit_data.zip", "./data")
  
  datamodule = SpeechRecognitionData.from_json(
      input_fields="file",
      target_fields="text",
      train_file="data/timit/train.json",
      test_file="data/timit/test.json",
      batch_size=4,
  )
  
  #####2.Build the task
  model = SpeechRecognition(backbone="facebook/wav2vec2-large-960h-lv60-self")
  
  ##### 3. Create the trainer and finetune the model
  trainer = flash.Trainer(max_epochs=1)
  trainer.finetune(model, datamodule=datamodule, strategy="no_freeze")
  
  ##### 4. Predict on audio files!
  datamodule = SpeechRecognitionData.from_files(predict_files=["data/timit/example.wav"], batch_size=4)
  predictions = trainer.predict(model, datamodule=datamodule)
  print(predictions)
  
  ##### 5. Save the model!
  trainer.save_checkpoint("speech_recognition_model.pt")
  
  import librosa
  #####transcribe audio files into chunks
  def asr_transcript(tokenizer, model, audio_file, clip_length):
      transcript = ""
  
      stream = librosa.stream(
          audio_file, block_length=clip_length, frame_length=16000, hop_length=16000
      )
  
      for speech in stream:
          if len(speech.shape) > 1:
              speech = speech[:, 0] + speech[:, 1]
  
          input_values = tokenizer(speech, return_tensors="pt").input_values
          logits = model(input_values).logits
  
          predicted_ids = torch.argmax(logits, dim=-1)
          transcription = tokenizer.decode(predicted_ids[0])
          transcript += transcription.lower() + ". " # this places an artifical full-stop at the end of each clip
          
      return transcript
  
  
  model_transcribe = SpeechRecognition.load_from_checkpoint("speech_recognition_model.pt")
  from transformers import Wav2Vec2ForCTC,Wav2Vec2Tokenizer,pipeline,Wav2Vec2CTCTokenizer
  tokenizer_transcribe = Wav2Vec2CTCTokenizer.from_pretrained("facebook/wav2vec2-large-960h-lv60-self")
  
  audio_file = "sample_audio.wav"
  clip_length = 25 # Stream over 25-second chunks
  transcript = asr_transcript(tokenizer_transcribe,model_transcribe, audio_file, clip_length)
  print(transcript)

#### Error Message:

----> 4 transcript = asr_transcript(tokenizer_transcribe,model_transcribe, audio_file, clip_length)
      5 print(transcript)

C:\Users\AVIJIT~1\AppData\Local\Temp/ipykernel_16544/1210495687.py in asr_transcript(tokenizer, model, audio_file, clip_length)
     14             speech = speech[:, 0] + speech[:, 1]
     15 
---> 16         input_values = tokenizer(speech, return_tensors="pt").input_values
     17         logits = model(input_values).logits
     18 

C:\conda\lib\site-packages\transformers\tokenization_utils_base.py in __call__(self, text, text_pair, add_special_tokens, padding, truncation, max_length, stride, is_split_into_words, pad_to_multiple_of, return_tensors, return_token_type_ids, return_attention_mask, return_overflowing_tokens, return_special_tokens_mask, return_offsets_mapping, return_length, verbose, **kwargs)
   2390 
   2391         if not _is_valid_text_input(text):
-> 2392             raise ValueError(
   2393                 "text input must of type `str` (single example), `List[str]` (batch or single pretokenized example) "
   2394                 "or `List[List[str]]` (batch of pretokenized examples)."

ValueError: text input must of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

**Comment by aribornstein** [comment]
@ethanwharris

**Comment by flozi00** [comment]
In HF master they are working on chunking files for CTC models to transcribe larger ones
