### ISSUE TITLE
Integrate PyTorchVideo detection models

### ISSUE THREAD

**Issue by Actis92** [PyTorchLightning/lightning-flash#1104]
In Lightning Flash is used PyTorchVideo for the classification problems, but we can extend it also for the detection part, since they are integrated in PyTorchVideo as you can see in this link https://pytorchvideo.org/docs/tutorial_torchhub_detection_inference.

Let me know if you can think can be useful to integrate this part, in that case I can work on the integration :)

**Comment by ethanwharris** [comment]
Hey @Actis92 yeah this is definitely something we're interested in. Would make a great addition to Flash. Let us know if you get blocked on anything :smiley:
