### ISSUE TITLE
Add required dependencies error message to `available_*` methods.

### ISSUE THREAD

**Issue by martin0258** [PyTorchLightning/lightning-flash#1125]
### To Reproduce

Code to reproduce the behavior:

```python
from flash.image import KeypointDetector

print(len(KeypointDetector.available_backbones())) # Output: 0
print(len(KeypointDetector.available_heads())) # Output: 0
```

### Expected behavior

I'm not sure what are all the available backbones and heads for `KeypointDetector`. However, from the source code of [KeypointDector](https://lightning-flash.readthedocs.io/en/stable/_modules/flash/image/keypoint_detection/model.html#KeypointDetector) (see the excerpt below) there should be at least 1 available backbones and heads, respectively.

```python
backbone: Optional[str] = "resnet18_fpn",
head: Optional[str] = "keypoint_rcnn",
```

### Environment

 - PyTorch Version (e.g., 1.0): 1.7.1+cu110
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, source): `pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 -f https://download.pytorch.org/whl/torch_stable.html`
 - Build command you used (if compiling from source): NA
 - Python version: 3.8.10
 - CUDA/cuDNN version: 
 - GPU models and configuration: RTX3090
 - Any other relevant information: Flash version 0.6.0

**Comment by ethanwharris** [comment]
Hey @martin0258 in order for the backbones to be available you would need to install `icevision` and `lightning-flash[image]`. So you could do the following:
```
pip install --upgrade icevision lightning-flash[image]
```

Hope that helps :smiley:

**Comment by martin0258** [comment]
Thank you @ethanwharris! It's working after I ran `pip install icevision==0.8.0`. Below is the result

```python
In [1]: from flash.image import KeypointDetector

In [2]: KeypointDetector.available_backbones()
Out[2]: 
['mobilenet',
 'resnet101',
 'resnet101_fpn',
 'resnet152',
 'resnet152_fpn',
 'resnet18',
 'resnet18_fpn',
 'resnet34',
 'resnet34_fpn',
 'resnet50',
 'resnet50_fpn',
 'resnext101_32x8d',
 'resnext101_32x8d_fpn',
 'resnext50_32x4d_fpn',
 'wide_resnet101_2_fpn',
 'wide_resnet50_2_fpn']

In [3]: KeypointDetector.available_heads()
Out[3]: ['keypoint_rcnn']
```

Just FYI: I installed icevision 0.8.0 because the latest icevision isn't compatible with my existing PyTorch 1.7.1+cu110. Also, previously I have already installed `lightning-flash[image]` with `pip install 'lightning-flash[image]'`. Your command `pip install lightning-flash[image]` would cause error `zsh: no matches found: lightning-flash[image]`.

My last question: Is it documented somewhere? I mean the knowledge of `in order for the backbones and heads to be available we would need to install icevision and lightning-flash[image]`.

**Comment by ethanwharris** [comment]
Hi @martin0258 glad you got it working! 

> My last question: Is it documented somewhere? I mean the knowledge of `in order for the backbones and heads to be available we would need to install icevision and lightning-flash[image]`.

Great question! It should have been, for other methods you would receive an error message letting you know what to install, but it looks like we missed it for these. I'll leave this issue open as a bug report to add the message. Hope that helps :smiley:
