### ISSUE TITLE
How to write a CustomTransformation that can take init-params?

### ISSUE THREAD

**Issue by daMichaelB** [PyTorchLightning/lightning-flash#1126]
#### What is your question?

I implemented a Custom Transformation like the `ImageClassificationInputTransform` documented here: https://lightning-flash.readthedocs.io/en/stable/reference/image_classification.html

When i use the example without any changes it works as expected ✅ 

However i have not found a good way to pass parameters into the `ImageClassificationInputTransform`.

```python
datamodule = ImageClassificationData.from_folders(
    train_folder="data/hymenoptera_data/train/",
    val_folder="data/hymenoptera_data/val/",
    train_transform=ImageClassificationInputTransform(image_size=(64,64)), # <---- that does not work
    transform_kwargs=dict(image_size=(128, 128)),
    batch_size=1,
)
```

whenever i pass the image_size, i get the following error

```
/usr/local/lib/python3.8/dist-packages/flash/core/data/io/input_transform.py in __post_init__(self)
    108         self._collate_in_worker_from_transform: Optional[bool] = None
    109         self._transform = None
--> 110         self._transform = self._check_transforms(self._resolve_transforms(self.running_stage), self.running_stage)
    111 
    112         # Hack

/usr/local/lib/python3.8/dist-packages/flash/core/data/io/input_transform.py in _resolve_transforms(self, running_stage)
    923 
    924         transforms_out = {}
--> 925         stage = _STAGES_PREFIX[running_stage.value]
    926 
    927         # iterate over all transforms hook name

AttributeError: 'property' object has no attribute 'value'
```

#### What have you tried?

It seems that when creating an instance from the dataclass, it sets `running_stage`=None and fails.

* I have tried to give it a `__init__` and remove the `@dataclass`

One can workaround this by adding a classmethod-setter function, like:

```python
        transforms = ImageClassificationInputTransform
        transforms.set_params(self.params)
```

I guess there is a better way ?! thank you

#### What's your environment?

 - OS: [e.g. iOS, Linux, Win] Ubuntu
 - Packaging [e.g. pip, conda] pip
 - Version [e.g. 0.5.2.1] 0.6.0

**Comment by ethanwharris** [comment]
Hey @daMichaelB thanks for the question! Anything passed to the `transform_kwargs` will be used when instantiating the transform, so the recommended way for your use case would be:
```
datamodule = ImageClassificationData.from_folders(
    train_folder="data/hymenoptera_data/train/",
    val_folder="data/hymenoptera_data/val/",
    train_transform=ImageClassificationInputTransform,
    transform_kwargs=dict(image_size=(64, 64)),
    batch_size=1,
)
```

This is a new API for us so we are still working out some things. If you wanted different image sizes for train / val / test then you could create an InputTransform object with `train_image_size` etc. arguments. What's a bit clunky is that you would have to pass `train_transform`, `test_transform`, `val_transform` etc. when creating your datamodule. Perhaps this would be cleaner:
```
datamodule = ImageClassificationData.from_folders(
    train_folder="data/hymenoptera_data/train/",
    val_folder="data/hymenoptera_data/val/",
    transform=ImageClassificationInputTransform,
    transform_kwargs=dict(train_image_size=(64, 64), eval_image_size=(128, 128), ...),
    batch_size=1,
)
```

Would love to hear your thoughts around this if you have any ideas for how we can improve it :smiley: As it's a new API we are quite flexible

**Comment by daMichaelB** [comment]
Hey @ethanwharris thanks for the detailed answer!! NICE 👍  i was not aware of the `transform_kwargs`. I think that is a pretty good solution and i will try it out now! 

IMHO the idea of having the transforms separated into `train_transform`/`valid_transform` and `test_transform` is great. It's more code but it is easier to keep the overview of what happens.

Thanks for your great support again!

**Comment by daMichaelB** [comment]
I close this as it is now clear, thanks!
