### ISSUE TITLE
Index out of error

### ISSUE THREAD

**Issue by Zumbalamambo** [PyTorchLightning/lightning-flash#115]
It throws the following error on training

```
self_supervised/simclr/simclr_module.py", line 249, in optimizer_step
    param_group["lr"] = self.lr_schedule[self.trainer.global_step]
IndexError: index 900 is out of bounds for axis 0 with size 900
```

**Comment by aribornstein** [comment]
@ananyahjha93

**Comment by akihironitta** [comment]
Maybe the same as https://github.com/PyTorchLightning/pytorch-lightning-bolts/issues/436?

**Comment by Zumbalamambo** [comment]
@akihironitta that seems to be working... I will check until it completes all the epoch. Have you tried changing the input_width to 640?

**Comment by Zumbalamambo** [comment]
Still the same problem even after I have set the max_epochs :(

**Comment by ananyahjha93** [comment]
@Zumbalamambo are you using the simclr/swav script from bolts? If yes, can you post the num samples in your dataset, your batch size, accelerator count and then max epochs?

**Comment by pengbohua** [comment]
I met the same issue when I tried to reproduce SwAV pretraining on CIFAR10. 

# data
batch_size = 2048
dm = CIFAR10DataModule(data_dir='./data/', batch_size=batch_size, normalize=True)
# loaders are contained in the DataModule which are self consistent

parser = argparse.ArgumentParser('SwAV CIFAR-10')
parser = SwAV.add_model_specific_args(parser)

args = parser.parse_args('')

# model
args.gpus = 1
args.arch = 'resnet18'
args.hidden_mlp = 1024
args.max_epochs = 100
args.dataset = dm
args.batch_size = batch_size
args.size_crops = [32, 16]
args.maxpool1 = False
args.nmb_crops = [2, 1]
args.gaussian_blur = False
args.num_samples = dm.num_samples
dm.train_transforms = SwAVTrainDataTransform(
    size_crops=args.size_crops,
    nmb_crops=args.nmb_crops,
    gaussian_blur=args.gaussian_blur
)

dm.val_transforms = SwAVEvalDataTransform(
    size_crops=args.size_crops,
    nmb_crops=args.nmb_crops,
    gaussian_blur=args.gaussian_blur
)
dm.test_transforms = SwAVEvalDataTransform(
    size_crops=args.size_crops,
    nmb_crops=args.nmb_crops,
    gaussian_blur=args.gaussian_blur
)
print('hypers', args)

#logger 
from pytorch_lightning.loggers import TensorBoardLogger, CSVLogger

csv_logger = CSVLogger("/content/drive/MyDrive/contrastive_learning/Swav/logs", name="SwAV-CIFAR10")
model = SwAV(
**args.__dict__
)


# fit
trainer = pl.Trainer(max_epochs=args.max_epochs, gpus=1, precision=16, logger=csv_logger, callbacks=[EarlyStopping(monitor='val_loss')])
trainer.fit(model, datamodule=dm)

**Comment by edgarriba** [comment]
@Zumbalamambo are you still having those issues ?
BTW, what version of flash do you use ?

**Comment by tarunn2799** [comment]
@edgarriba I'm facing the same issue, when I'm trying to train a custom dataset.  I'm running 4 gpus, and a batch size of 2048.

**Comment by ananyahjha93** [comment]
This has been fixed in bolts master.
