### ISSUE TITLE
Create `FlashRegistry` of Available Heads for `flash.image.ImageClassifier`

### ISSUE THREAD

**Issue by AjinkyaIndulkar** [PyTorchLightning/lightning-flash#1150]
Hey folks! This is my first time opening an issue here. Great project!

## ❓ Questions and Help

After reading the documentation as well as source code, I find that `flash.image.ImageClassifier` has no flash registry for available heads. There's one for all other `flash.image` tasks but not the classification task.

Right now, the only way I see to add a heads registry is to create a new class, inherit from `flash.image.ImageClassifier`, copy and update the `__init__()` method to fetch heads from a registry. 

Is there an easy way to do this? Although it's possible to create a `nn.module` for the head and pass it to `flash.image.ImageClassifier`, I would like to keep a registry and simply pass the head id and additional kwargs, just like one would do for loading the model backbone.

**Comment by ethanwharris** [comment]
Hey @AjinkyaIndulkar Thanks for the question! A registry for classification heads is a great suggestion! I'll recategorize this issue as a feature request to add it. Would you be interested in working on this?

**Comment by ethanwharris** [comment]
Awesome!!! Let us know if you need help with anything and feel free to open a PR even if you just have something you'd like to get some feedback one :smiley:

**Comment by AjinkyaIndulkar** [comment]
alright! I'll go through the contributing guidelines first and reach out if something is unclear.
