### ISSUE TITLE
Object detection example brakes

### ISSUE THREAD

**Issue by oddeirikigland** [PyTorchLightning/lightning-flash#1151]
## 🐛 Bug

[The example](https://lightning-flash.readthedocs.io/en/latest/reference/object_detection.html) breaks when finetune is called.

After initialization of the datamodule (before finetuning is called) the batch size is correct and the image size is set to 128 for all input.

Inside the finetune call the input sizes seems to be reset which creates the problem. Error message:

```
batch_images = torch.stack(batch_images)
RuntimeError: stack expects each tensor to be equal size, but got [3, 640, 480] at entry 0 and [3, 425, 640] at entry 1
```

### To Reproduce

1. [Follow the example](https://lightning-flash.readthedocs.io/en/latest/reference/object_detection.html)

#### Code sample

```
import flash
from flash.core.data.utils import download_data
from flash.image import ObjectDetectionData, ObjectDetector

# 1. Create the DataModule
# Dataset Credit: https://www.kaggle.com/ultralytics/coco128
download_data("https://github.com/zhiqwang/yolov5-rt-stack/releases/download/v0.3.0/coco128.zip", "data/")

datamodule = ObjectDetectionData.from_coco(
    train_folder="data/coco128/images/train2017/",
    train_ann_file="data/coco128/annotations/instances_train2017.json",
    val_split=0.1,
    transform_kwargs={"image_size": 128},
    batch_size=4,
)

# 2. Build the task
model = ObjectDetector(head="efficientdet", backbone="d0", num_classes=datamodule.num_classes, image_size=128)

# 3. Create the trainer and finetune the model
trainer = flash.Trainer(max_epochs=1)
trainer.finetune(model, datamodule=datamodule, strategy="freeze")

# 4. Detect objects in a few images!
datamodule = ObjectDetectionData.from_files(
    predict_files=[
        "data/coco128/images/train2017/000000000625.jpg",
        "data/coco128/images/train2017/000000000626.jpg",
        "data/coco128/images/train2017/000000000629.jpg",
    ],
    transform_kwargs={"image_size": 128},
    batch_size=4,
)
predictions = trainer.predict(model, datamodule=datamodule)
print(predictions)

# 5. Save the model!
trainer.save_checkpoint("object_detection_model.pt")
```

### Expected behavior

A running example.

### Environment

 - PyTorch Version (e.g., 1.0): 1.10.2
 - OS (e.g., Linux): MAC M1
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.9.6
 - CUDA/cuDNN version: CPU
 - GPU models and configuration:
 - Any other relevant information:

**Comment by ethanwharris** [comment]
Hey @oddeirikigland thanks for reporting this! We've recently fixed a few bugs there. Could you. install flash from github with:
```
pip install 'git+https://github.com/PyTorchLightning/lightning-flash.git#egg=lightning-flash[image]'
```
And see if you still get the error?

Thanks :smiley:

**Comment by oddeirikigland** [comment]
@ethanwharris It worked with the github install, thank you!
