### ISSUE TITLE
mmsegmentation support

### ISSUE THREAD

**Issue by bowenroom** [PyTorchLightning/lightning-flash#1156]
mmsegmentation package(https://mmsegmentation.readthedocs.io/en/latest/get_started.html) has been used in many research papers.Is there any plans for the combination of lightning-flash and mmsegmentation? we can see that [segmentation_models.pytorch](https://github.com/qubvel/segmentation_models.pytorch) is supported, but mmsegmentation support more lateast models and we all look forward to the combination of both two!

**Comment by ethanwharris** [comment]
Hi @bowenroom We don't have anyone working on MMSegmentation support currently but it's definitely an integration we'd like to have. I've marked this issue as a feature request, is this something you'd be interested in trying to contribute to Flash?

**Comment by bowenroom** [comment]
Thanks for the reply from @ethanwharris. I wish to contribute to pytorch-lightning Flash, but I am still a green hand to the deep learning implementation. After polishing some skills, I will make every effort for the contribution! Appreciate for the reply and the contribution from lightning team, big thanks!
