### ISSUE TITLE
Text Embedder Docs are missing/incomplete

### ISSUE THREAD

**Issue by charleswm** [PyTorchLightning/lightning-flash#1159]
## 📚 Documentation

https://lightning-flash.readthedocs.io/en/latest/reference/text_embedder.html

I saw in the 0.6 release notes that TextEmbedder was added (#996), so I went to look at the docs for how to use it. Unfortunately, there's just a stub there right now. Wanted to raise in case it was an oversight.

![image](https://user-images.githubusercontent.com/11549389/153332509-e696bf5d-0cc6-4f71-a682-068e625b25c5.png)

![image](https://user-images.githubusercontent.com/11549389/153332333-31d31f5f-cdbe-478e-a611-58bc9cc739fc.png)

**Comment by ethanwharris** [comment]
Hey @charleswm Thanks for reporting this! This looks like a bug in our docs. There should be a full example there, and looks like a broken link too! I'll look into it :smiley:
