### ISSUE TITLE
utility to manage the cropping per the Alexnet, Resnet-50, and Googlenet papers

### ISSUE THREAD

**Issue by yaoshiang-masterfulai** [PyTorchLightning/lightning-flash#1202]
## 🚀 Feature
Does PyTorch Lightning have a utility to manage the cropping per the Alexnet, Resnet-50, and Googlenet papers? I always get burned trying to do it myself and I have to look it up every time... Resnet50 paper says they adopt Alexnet's "10-crop testing" but I don't see a reference to this cropping in the alexnet paper, and it's not obvious from the alexnet source. In testing, for comparison studies we adopt the standard 10-crop testing [21 (which is Alexnet)].

### Motivation

Easily reproduce classic architectures. 

### Pitch

Utility to handle cropping to achieve benchmark results in classic research papers. 

### Alternatives

Hand implement it.

**Comment by ethanwharris** [comment]
Hi @yaoshiang-masterfulai Torchvision has a TenCrop transform: https://pytorch.org/vision/main/generated/torchvision.transforms.TenCrop.html - there is an example there on how it can be used to perform 10-crop testing. I don't think PL supports test-time-augmentation out of the box but it could be done by modifying your test step. Hope that helps :smiley:
