### ISSUE TITLE
New Video Tasks

### ISSUE THREAD

**Issue by austinmw** [PyTorchLightning/lightning-flash#1207]
## 🚀 Feature
I'd like to request new tasks for:
- Video object detection (models which use multi-frame information to improve detection quality compared to single-frame detection)
- Video multi-object tracking (using either single-frame or multi-frame detection, but then associating boxes with tracks over time) 

### Motivation

These are two very common tasks, but I can't seem to find pytorch lightning implementations for either of them.

### Pitch

There's several models available for each. I'd maybe suggest [ByteTrack](https://github.com/ifzhang/ByteTrack) for the MOT task and [Temporal RoI Align](https://github.com/open-mmlab/mmtracking/tree/master/configs/vid/temporal_roi_align) for video object detection task, though any models that strike a good balance between ease of integration and performance would be great additions.

### Alternatives
The only alternative I know of is using the standalone mmtracking library, though I'd love to be able to use lightning's features.

**Comment by ethanwharris** [comment]
Hi @austinmw Thanks for the feature request! Definitely keen to have more video tasks in Flash :smiley:

**Comment by tchaton** [comment]
Dear @[austinmw](https://github.com/austinmw),

Yes, video support would be great. We started with PyTorchVideo but their development has stopped.

There is this very interesting repo we could integrate to get started: https://github.com/mcahny/vps

Would you have any interest in trying to do so with our help ?

Best,
T.C

**Comment by austinmw** [comment]
Thanks for your response. That does seem like an interesting library. Would the idea be that it could also accomplish the sub problems of video object detection, video semantic segmentation and video instance segmentation?

I don't have free time this week, but could potentially look into it more in another 1-2 weeks.

**Comment by addisonklinke** [comment]
Any more recent thoughts on this? Object tracking in videos is also a very common task in my day-to-day work

I would add [TrackNet (U-Net)](https://nol.cs.nctu.edu.tw:234/open-source/TrackNetv2) to the list of candidate models. Particularly the 3-frame input variation which provides some temporal context for the predictions. I've worked on a PyTorch port of the original Keras implementation previously, so I could consider setting that up for Flash with some guidance
