### ISSUE TITLE
add instance segmentation example for voc dataset from icedata

### ISSUE THREAD

**Issue by joowon-dm-snu** [PyTorchLightning/lightning-flash#1214]
### Motivation

I thought `icedata.pets` are not practical enough for users and 
  hope `InstanceSegmentationData.from_voc`  supports `icedata` compatibilities more.

### Pitch

```python
datamodule = InstanceSegmentationData.from_voc(
    provider='icedata'
    val_split=0.1,
    batch_size=1,
)
```

### Additional context

I currently write code below for using `icedata.voc`.
```python
data_dir = icedata.voc.load_data()

datamodule = InstanceSegmentationData.from_icedata(
    train_folder=data_dir / "JPEGImages",
    train_ann_file=data_dir / "Annotations",
    parser=icevision.parsers.VOCMaskParser,
    train_parser_kwargs={
        "class_map": icedata.voc.class_map(),
        "masks_dir": data_dir / "SegmentationObject",
    },
    val_split=0.1,
    batch_size=1,
)
```

But `icevision` has to solve some issues before make integration here.
I reported 2 issues in their repo.  
  - https://github.com/airctic/icevision/issues/1072
  - https://github.com/airctic/icevision/issues/1073

Could you add new integration or example for `icedata.voc` in `InstanceSegmentation` after they solve that issues?

**Comment by ethanwharris** [comment]
Hi @joowon-dm-snu Thanks for the question. Did you see the from_voc method? Here is it's docstring: https://lightning-flash.readthedocs.io/en/stable/api/generated/flash.image.instance_segmentation.data.InstanceSegmentationData.html#flash.image.instance_segmentation.data.InstanceSegmentationData.from_voc

It uses icevision internally so may still have the issues you linked, but might be worth a try :smiley:
Hope that helps!

**Comment by joowon-dm-snu** [comment]
@ethanwharris  thanks for reply. Your suggestion runs well and much more clear :)

here's memo for using `icedata.voc` directly
```python
import icedata 
from flash.image import InstanceSegmentationData

data_dir = icedata.voc.load_data()

datamodule = InstanceSegmentationData.from_voc(
    icedata.voc.data._CLASSES,
    train_folder=data_dir / "JPEGImages",
    train_ann_folder=data_dir / "Annotations",
    train_target_folder=data_dir / "SegmentationObject",
    val_split=0.1,
    batch_size=8,
)
```
