### ISSUE TITLE
Object detection multi-gpu problem

### ISSUE THREAD

**Issue by EldorIbragimov** [PyTorchLightning/lightning-flash#1230]
## 🐛 Bug

Could not train on multi-gpu mode for Yolov5 model on object detection. But it works on single gpu
### To Reproduce

![image](https://user-images.githubusercontent.com/26270045/158292172-e13a763e-ec82-4c47-b19a-6c872574010a.png)

#### Code sample
`
model = ObjectDetector(head='yolov5', backbone='extra_large_p6', num_classes=datamodule.num_classes, image_size=128)

trainer = flash.Trainer(max_epochs=100, gpus=[0,1], strategy="ddp")

trainer.finetune(model, datamodule=datamodule,strategy="freeze") `

### Environment

 - OS (e.g., Linux):
 - Python version: 3.8
 - PyTorch/Lightning/Flash Version (e.g., 1.10/1.5/0.7): Latest
 - GPU: four 3090 gpu, 
 - Any other relevant information:

**Comment by ethanwharris** [comment]
Hey @EldorIbragimov thanks for reporting this! I think it's not currently possible for us to support DDP, but I am working on a fix for DDP_SPAWN in #1222 :smiley:

**Comment by ethanwharris** [comment]
Closing this as it should now be working with DDP_Spawn following #1222. - please feel free to re-open if that doesn't resolve your issue :smiley:
