### ISSUE TITLE
Save augmented images for debugging (extension of SemanticSegmentationData?)

### ISSUE THREAD

**Issue by andife** [PyTorchLightning/lightning-flash#1236]
## 🚀 Feature
For the purpose of semantic segmentation, it would be nice to be able to save the augmented images (after kornia, albumentations, icevision...) for debugging purposes .

### Motivation

For debugging purposes it would be aweome to see, how the selected parameters affect the images. Of course this could be done separately, but it would be great if there was the possibility to save the date with simple flags. 

### Pitch

I would suggest additional flags in SemanticSegmentationData with "saveImagesTrue" or/and a folderpath for storing these data 

### Alternatives

No hard directly integrated functionality, but an example how to use existing functions to restore this behavoir.

**Comment by ethanwharris** [comment]
Hi @andife, thanks for the feature request! We did previously have some callback functionality that would allow you to access the samples / batch at various points in the pipeline. It has issues at the moment but is something we could look to clean up to enable this sort of use case 😃
