### ISSUE TITLE
ImageEmbedder not working

### ISSUE THREAD

**Issue by sirtris** [PyTorchLightning/lightning-flash#1258]
## 🐛 Bug

When I try to use the ImageEmbedder I get the following error message:
`ModuleNotFoundError: Required dependencies not available. Please run: pip install 'vissl' 'fairscale' 'lightning-flash[image]'`

I insalled `vissl` as described on their website using conda.  
I have:
`vissl.__version__ = 0.1.6`
`fairscale.__version__ = 0.3.7`
`flash.__version__ = 0.7.1`
`torch.__version__ = 1.7.1`

### To Reproduce

Run the code from the lightning_flash doc example:

```python
import torch
from torchvision.datasets import CIFAR10

import flash
from flash.core.data.utils import download_data
from flash.image import ImageClassificationData, ImageEmbedder

# 1. Download the data and prepare the datamodule
datamodule = ImageClassificationData.from_datasets(
    train_dataset=CIFAR10(".", download=True),
    batch_size=16,
)

# 2. Build the task
embedder = ImageEmbedder(
    backbone="resnet",
    training_strategy="barlow_twins",
    head="barlow_twins_head",
    pretraining_transform="barlow_twins_transform",
    training_strategy_kwargs={"latent_embedding_dim": 128},
    pretraining_transform_kwargs={"size_crops": [196]},
)
```

### Expected behavior

Run without error

### Environment

 - OS (e.g., Linux): Pop!_OS 21.10
 - Python version: 3.8.13
 - Relevant python dependencies described above.

**Comment by ethanwharris** [comment]
Hi @sirtris Thanks for reporting this! This is working ok for me locally and in our CI. Could you share the command you used to install Flash? It would need to be `pip install 'lightning-flash[image]'` for this example to work

**Comment by sirtris** [comment]
Thanks that solved it.
I was only using `pip install lightning-flash`
