### ISSUE TITLE
Flash fails to load image labels from CSV on Kaggle RANZCR CLiP - Catheter and Line Position Challenge

### ISSUE THREAD

**Issue by aribornstein** [PyTorchLightning/lightning-flash#126]
## 🐛 Bug

The master code does not properly load labels from CSV for image classification. Trying to get a baseline working for the Catheter and Line Position Challenge and am currently blocked. 

 

### To Reproduce

1. !pip install git+https://github.com/PyTorchLightning/lightning-flash.git@master
2. Run '....'
```python

import os
import flash
from flash.core.data import download_data
from flash.core.finetuning import FreezeUnfreeze
from flash.vision import ImageClassificationData, ImageClassifier

data = ImageClassificationData(
    train_filepaths='/kaggle/input/ranzcr-clip-catheter-line-classification/train', 
    train_labels='/kaggle/input/ranzcr-clip-catheter-line-classification/train.csv', 
    valid_filepaths='/kaggle/input/ranzcr-clip-catheter-line-classification/test', 
    valid_labels='/kaggle/input/ranzcr-clip-catheter-line-classification/test.csv'
)

```

### Stack Trace

Successfully installed datasets-1.2.1 lightning-flash-0.2.1.dev0 pandas-1.1.2 pycocotools-2.0.2 pytorch-lightning-1.2.0rc0 pytorch-lightning-bolts-0.3.0 pytorch-tabnet-3.1.1 rouge-score-0.0.4 scikit-learn-0.24.0 torch-1.7.1 torchvision-0.8.2 tqdm-4.49.0 xxhash-2.0.0
TypeError
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-1ea2eb98cece> in <module>
      3     train_labels='/kaggle/input/ranzcr-clip-catheter-line-classification/train.csv',
      4     valid_filepaths='/kaggle/input/ranzcr-clip-catheter-line-classification/test',
----> 5     valid_labels='/kaggle/input/ranzcr-clip-catheter-line-classification/test.csv'
      6 )

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/core/datamodule.py in __call__(cls, *args, **kwargs)
     48 
     49         # Get instance of LightningDataModule by mocking its __init__ via __call__
---> 50         obj = type.__call__(cls, *args, **kwargs)
     51 
     52         return obj

TypeError: __init__() got an unexpected keyword argument 'train_filepaths'
__init__() got an unexpected keyword argument 'train_filepaths'
Enter console command here

### Expected behavior

Data Module loads labels without issue

**Comment by edenlightning** [comment]
Looks like we need to update the docs on how to pass in train_labels.

**Comment by aribornstein** [comment]
In the code it makes it seem as if you can pass a file. Will also claimed that he had this working is it possible something changed?

See line 304

https://github.com/PyTorchLightning/lightning-flash/blob/master/flash/vision/classification/data.py

**Comment by teddykoker** [comment]
You need to use `ImageClassificationData.from_filepaths`, and then supply the filenames and labels as lists

**Comment by aribornstein** [comment]
Yes that's something missing from the prediction interface a way to see the labels and a way to get the prediction class distribution.

**Comment by williamFalcon** [comment]
https://github.com/PyTorchLightning/lightning-flash/blob/master/flash/data/data_utils.py#L6
