### ISSUE TITLE
align with PR 1.2.0

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/lightning-flash#132]
## 🚀 Feature

Atm, we have a hard link to 1.2.0rc0 which is a bit outdated...
Probably some API adjust need to be done, continue in #62

**Comment by carmocca** [comment]
This needs `skip_collate_fn` in Lightning https://github.com/PyTorchLightning/lightning-flash/blob/c505c586e0c85aa1a6843d8f67c934379ef1b9a1/flash/core/model.py#L121

https://github.com/PyTorchLightning/internal-dev/issues/96

@kaushikb11

**Comment by kaushikb11** [comment]
@carmocca But aren't we overriding the `predict` method in our Task class?

**Comment by carmocca** [comment]
Just synced with @justusschock and we won't need it anymore.
