### ISSUE TITLE
Pass Trainer Arguments into Model.predict

### ISSUE THREAD

**Issue by aribornstein** [PyTorchLightning/lightning-flash#145]
## 🚀 Feature
I should have a way to override the predict trainer in model.predict

### Motivation

Flashes model.predict doesn't support features like distributed inference this causes pretty significant bottlenecks when evaluating large models we need a way of streamlining this so evaluation will be faster.

**Comment by edgarriba** [comment]
@aribornstein can you describe a bit more the api that would you like here ?

**Comment by edenlightning** [comment]
@aribornstein closing this, reopen with more context if needed
