### ISSUE TITLE
Onnx Runtime Predict 

### ISSUE THREAD

**Issue by aribornstein** [PyTorchLightning/lightning-flash#146]
## 🚀 Feature

Onnx Runtime can significantly speed up prediction it would be interesting to have some capability to internally convert and inference model using Onnx runtime automatically in the trainer. 

### Motivation

https://www.youtube.com/watch?v=WDww8ce12Mc

**Comment by edgarriba** [comment]
Cannot this achieved via lightning ? /cc @Borda
