### ISSUE TITLE
ImageClassificationData.from_arrays

### ISSUE THREAD

**Issue by aribornstein** [PyTorchLightning/lightning-flash#151]
## 🚀 Feature
In addition from data reading from file paths it should be possible to image data and labels from numpy arrays like required in the mnist kaggle challenge. https://www.kaggle.com/c/digit-recognizer

### Motivation

Data processing in Flash needs to be improved there are many different ways to ingest data but flash requires data to be in folders for image classification this forces users to do inefficient preprocessing to use flash for basic scenarios. This needs to be improved.

**Comment by edgarriba** [comment]
@aribornstein what would be your ideal api here - something like ?

```python
dm = ImageClassificationData.from_arrays(data: List[np.ndarray], List[int]):
  ...
```

**Comment by ethanwharris** [comment]
Following #256 you should now be able to do `ImageClassificationData.from_numpy(train_data: ndarray, train_targets: List[Any], ...)`

**Comment by aribornstein** [comment]
Amazing!!!
