### ISSUE TITLE
Add split support in from folders

### ISSUE THREAD

**Issue by aribornstein** [PyTorchLightning/lightning-flash#152]
## 🚀 Feature

From ImageClassificationData.from_filepaths allows me to define splits for validation but from ImageClassificationData.from_folders does not this is inconsistent and should be a standard feature.

**Comment by edgarriba** [comment]
@aribornstein this come after #141 . See: https://github.com/PyTorchLightning/lightning-flash/blob/44d70e16ae74f890376a2a52175ef9c43e2b0291/flash/data/data_module.py#L379
