### ISSUE TITLE
NLTK being loaded on image classifcation

### ISSUE THREAD

**Issue by aribornstein** [PyTorchLightning/lightning-flash#162]
### To Reproduce

```python
from flash.data import labels_from_csv
from flash.vision import ImageClassificationData
from flash.vision import ImageClassifier
from flash import Trainer
```

[nltk_data] Error loading punkt: <urlopen error [Errno -3] Temporary
[nltk_data]     failure in name resolution>

**Comment by edenlightning** [comment]
@aribornstein can you paste the error? and explain intended behaviour?

**Comment by aribornstein** [comment]
The error is already pasted 

```
[nltk_data] Error loading punkt: <urlopen error [Errno -3] Temporary
[nltk_data] failure in name resolution>
```

If I'm not using a NLP Task it makes no sense to load NLTK.

**Comment by aniketmaurya** [comment]
I would like to fix this.

**Comment by aniketmaurya** [comment]
Hi @aribornstein, since `__init__.py` of flash imports all the modules, the `text` module is also imported and ```nltk.download("punkt", quiet=True)``` is executed. This download should happen only when someone uses the library for the first time.

**Comment by edgarriba** [comment]
@edenlightning one thing I've been noticing is that some tasks like ImageClassification have pretrained weights set to True by default. Not sure if this can be related but the underlying libraries providing the backbones like torchvision have it to False I guess to avoid auto-downloading issues.

**Comment by kaushikb11** [comment]
@aniketmaurya Would you like to do a PR for this?

**Comment by aniketmaurya** [comment]
Yes @kaushikb11 I'd love to add a PR for this.
