### ISSUE TITLE
Cannot import name 'PY3' with Pytorch 1.8

### ISSUE THREAD

**Issue by edgarriba** [PyTorchLightning/lightning-flash#163]
## 🐛 Bug

I get the following error after a fresh install (which install pytorch 1.8) and  try to run the image classification example.

`ImportError: cannot import name 'PY3' from 'torch._six'` 

It turns out that installing 1.7.1 the script seems to work as expected - so some dependency in pytorch 1.8 make this to happen.

### To Reproduce

After creating a fresh venv
```bash
git clone https://github.com/PyTorchLightning/lightning-flash.git
cd lightning-flash
pip install -e .
python flash_examples/finetuning/image_classification.py
```

This is the full error message: https://pastebin.com/4xEtr5tv

**Comment by elcronos** [comment]
I got the same problem

**Comment by Borda** [comment]
@elcronos pls upgrade Bolts
`pip install -U lightning-bolts`
