### ISSUE TITLE
SWA not recognized by flash trainer

### ISSUE THREAD

**Issue by aribornstein** [PyTorchLightning/lightning-flash#173]
## 🐛 Bug

```python

trainer = Trainer(
    gpus=1,
    auto_lr_find=True,
    precision=16,
    stochastic_weight_avg=True,
    max_epochs=10,
    auto_scale_batch_size='binsearch',
    callbacks=[EarlyStopping(monitor='val_binary_cross_entropy_with_logits')]
)
trainer.finetune(clf, data, strategy='freeze_unfreeze')

```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-3d8c664be0b1> in <module>
      6     max_epochs=10,
      7     auto_scale_batch_size='binsearch',
----> 8     callbacks=[EarlyStopping(monitor='val_binary_cross_entropy_with_logits')]
      9 )
     10 trainer.finetune(clf, data, strategy='freeze_unfreeze')

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py in overwrite_by_env_vars(self, *args, **kwargs)
     39 
     40         # all args were already moved to kwargs
---> 41         return fn(self, **kwargs)
     42 
     43     return overwrite_by_env_vars

TypeError: __init__() got an unexpected keyword argument 'stochastic_weight_avg'

**Comment by Borda** [comment]
duplicate to #132
