### ISSUE TITLE
Error with custom transform dict

### ISSUE THREAD

**Issue by edgarriba** [PyTorchLightning/lightning-flash#183]
## 🐛 Bug

I'm using the branch `datapipeline_poc_1` and when I pass a custom dictionary with transforms with an unexpected key, the class do not raise any error, continues with the process and later as expected it crashes.

Here is the snippet:

```python

  train_transform = {
    "per_sample_transform": T.Compose([
    # "per_sample_pre_tensor_transform": T.Compose([
        T.RandomResizedCrop(224),
        T.RandomHorizontalFlip(),
        T.ToTensor(),
        T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ]),
    "per_batch_transform_on_device": nn.Sequential(
        K.RandomAffine(360), K.ColorJitter(0.2, 0.3, 0.2, 0.3))
    }

    data = ImageClassificationData.from_folders(
        # train_folder=os.path.join(root, 'train'), 
        train_folder=os.path.join(root),
        train_transform = train_transform,
    )
    assert data._train_dataloader() is not None
```

My guess is that this should be checked here with a meangful error
https://github.com/PyTorchLightning/lightning-flash/pull/141/files#diff-a0d6fd4ffd8169389e980176e6b2d667b37768e452c1e5abc3615f767dc85143R193

**Comment by edenlightning** [comment]
@edgarriba mind verifying if still persist on master?

**Comment by edgarriba** [comment]
this was fixed
