### ISSUE TITLE
data_pipeline.worker_preprocessor not working as expected

### ISSUE THREAD

**Issue by edgarriba** [PyTorchLightning/lightning-flash#184]
## 🐛 Bug

In the branch `datapipeline_poc_1` when I use `DataPipeline.worker_preprocess` if the input is `List[PIL.Image]` I get the following error:
`TypeError: pic should be PIL Image or ndarray. Got <class 'list'>`

### To Reproduce

```python
x: List[PIL.image] = [dataset[i] for i in range(self._data_module.batch_size)]
x: torch.Tensor = data_pipeline.worker_preprocessor(running_stage)(x)
```

### Additional context

The error seems to come from here:
https://github.com/PyTorchLightning/lightning-flash/blob/datapipeline_poc_1/flash/vision/classification/data.py#L193

which can be hacked as `return self.to_tensor(sample[0])` but not sure what else can be affected.
Where are those classes/methods tested ?

**Comment by edenlightning** [comment]
@edgarriba does this issue still persist on master?

**Comment by edgarriba** [comment]
fixed
