### ISSUE TITLE
Load custom backbones without attaching head

### ISSUE THREAD

**Issue by aribornstein** [PyTorchLightning/lightning-flash#187]
## 🚀 Feature
Today each time a backbone is loaded a custom head is attached this should be optional

**Comment by tchaton** [comment]
Hey @aribornstein,

Not sure to understand what you meant. Do you mean to convert a ImageClassifier into a ImageEmbedder ?

**Comment by edgarriba** [comment]
@aribornstein @tchaton this feature is already supported with new backbones API, right ?

**Comment by edenlightning** [comment]
@aribornstein open if needed
