### ISSUE TITLE
Trainer error on fine-tuning of TranslationTask following the examples

### ISSUE THREAD

**Issue by mabu-dev** [PyTorchLightning/lightning-flash#246]
## 🐛 Bug

Following the TranslationTask example, Trainer throws the error `TypeError: freeze() got an unexpected keyword argument 'module'` when calling `trainer.finetune`

### To Reproduce

Follow the [translation example](https://github.com/PyTorchLightning/lightning-flash/blob/master/flash_examples/finetuning/translation.py)

#### Code sample
Found here: https://github.com/PyTorchLightning/lightning-flash/blob/master/flash_examples/finetuning/translation.py

### Environment
[Google Colab](https://colab.research.google.com/drive/10IjyaxOgjeE1AvnH4EkNSLdO0DYSShS3?usp=sharing)

### Additional context
![image](https://user-images.githubusercontent.com/22409996/115975563-28853d80-a566-11eb-956c-8d0fdd6694c2.png)

**Comment by ethanwharris** [comment]
Hi @mabu-dev thanks for the issue :smiley: This has been fixed on the current master branch, which you can install using: `pip install git+https://github.com/PytorchLightning/lightning-flash.git@master`. Closing this, but please re-open if your issue is not resolved.
