### ISSUE TITLE
`from_csv` or `from_df` method in ImageClassificationData

### ISSUE THREAD

**Issue by aniketmaurya** [PyTorchLightning/lightning-flash#257]
## 🚀 Feature
Currently, ImageClassificationData has only from_folder and from_filepaths method. It would be helpful to have from_df or from_csv as well.

### Motivation

I was trying out https://www.kaggle.com/c/plant-pathology-2021-fgvc8/overview and the data is present in CSV format.

### Additional context

PS: I would like to contribute to this.

**Comment by edgarriba** [comment]
the DataModule API is under refactor in #256. After that I guess we can include methods like the ones you suggest. However, that api needs a bit of though since data coming dataframes or csv files can be in infinite formats and structures. /cc @ethanwharris

**Comment by ethanwharris** [comment]
Hi all, yeah best to leave this one until #256 is finished (hopefully won't be long). I agree with @edgarriba, but I think we should at least be able to provide some defaults for image and text classification - one field corresponds to the text / image file to classify, one or more fields (for multi-label) correspond to the target/s. That should be pretty easy to add with #256 :smiley:

**Comment by aniketmaurya** [comment]
I agree @ethanwharris! We should atleast capture default cases and may be provide some method to customise it may be by passing a function to load CSV and return X and Y values.
