### ISSUE TITLE
Backbones not found when library installed after flash is imported

### ISSUE THREAD

**Issue by ethanwharris** [PyTorchLightning/lightning-flash#265]
## 🐛 Bug

In a notebook setting it's pretty easy to end up installing a backbone library (e.g. `timm`) after flash has already been imported. When this happens the backbones won't be found as they are loaded when flash is imported.

There are a couple of options here:
- Just add a warning when a backbone isn't found to say 'if the backbone you're looking for is from an external library that lib needs to be installed __before__ you import flash'.
- We could bundle the registry creation into a method or something and re-run it if a backbone isn't found.

**Comment by Borda** [comment]
I would say it more issue of jupyter itself as you can do anything in any other, what I found, mostly recommended is restart runtime whenever you do some package installation...
