### ISSUE TITLE
add serialisation to object detection

### ISSUE THREAD

**Issue by edgarriba** [PyTorchLightning/lightning-flash#284]
## 🚀 Feature

Add serializes for object detection

### Motivation

At this moment object detection task returns a dict with tensors as result but we should be able to customize through an serialization object.

**Comment by bsridatta** [comment]
Hey, I am interested to work on this. This would be my first contribution to this repo though, let me know!

**Comment by akihironitta** [comment]
Hi @bsridatta, that would be great!

**Comment by bsridatta** [comment]
Thanks @akihironitta! 
Could you or @edgarriba give me some clarification. Just to make sure I understood the idea, `model.predict()` gives a list of dictionaries for each input image with keys `boxes, labels, scores`. The enhancement is to add optional param to save the list of dictionaries as JSON object or such?

**Comment by bsridatta** [comment]
@edgarriba @akihironitta  can I get clarity on this? Thanks
