### ISSUE TITLE
Remove the restriction of Bert Based models in TextClassification Task.

### ISSUE THREAD

**Issue by Atharva-Phatak** [PyTorchLightning/lightning-flash#294]
## 🚀 Feature
Remove the restriction of Bert Based models in TextClassification Task.

### Motivation
For classification I would like to use flash but I want independence to differ from bert based models.

### Pitch

*  I would like to propose that TextClassifier model, accepts "nn.Module" object for model argument rather than name of a bert based model. This will give the user the ability to create custom models which could have custom layers.
* Another suggestion is instead of accepting again backbone name for tokenizer, let the user create the tokenizer from hugging face.
* If the above are implemented essentially, we wont require transformers in requirements.txt, thus reducing additional dependency.

Note: This goes without saying, I would like to work on a PR if this issue is accepted. 😃

**Comment by edgarriba** [comment]
@Atharva-Phatak what you mention makes total sense. Before asking you to send a PR - I would suggest to check this active PR about adding a `token_classification` task and add some comments there. See: https://github.com/PyTorchLightning/lightning-flash/pull/275

**Comment by Atharva-Phatak** [comment]
@edgarriba Thank you very much I will go through the mentioned PR.

**Comment by Atharva-Phatak** [comment]
@edgarriba I did take a look at #275, it seems with the new release the branch is outdated. So what should I do now ? Should I create a PR for this issue ?
