### ISSUE TITLE
ModuleNotFoundError: newer version of lightning flash does not recognize Image module

### ISSUE THREAD

**Issue by SalmanLiaqat** [PyTorchLightning/lightning-flash#326]
Hi,
I have been working on object detection lightning flash but the newer version is not im
![1](https://user-images.githubusercontent.com/72979320/119102495-8442c980-ba33-11eb-945c-5e9ec6af11f0.JPG)
porting image module.

Please let me know how to fix these issues. 

Thanks and Regards!

**Comment by edgarriba** [comment]
@SalmanLiaqat As the error indicates, now you must install the image module dependencies with `pip install .[image]` from the root of the package

**Comment by ethanwharris** [comment]
@SalmanLiaqat @edgarriba You can also just do `pip install "lightning-flash[image]"` :smiley:

**Comment by SalmanLiaqat** [comment]
> @SalmanLiaqat @edgarriba You can also just do `pip install "lightning-flash[image]"` 😃

nops. still getting the same error

ModuleNotFoundError: Please, pip install . '[image]'

**Comment by ethanwharris** [comment]
@SalmanLiaqat Could you share the output of `pip list`?

**Comment by SalmanLiaqat** [comment]
> @SalmanLiaqat Could you share the output of `pip list`?
Thanks ethan, Got it working, probably some error in my directory
