### ISSUE TITLE
Acceptable values for metrics paramater in ObjectDetector

### ISSUE THREAD

**Issue by deepseek-eoghan** [PyTorchLightning/lightning-flash#358]
## ❓ Questions and Help

What are some examples of acceptable values for the metrics parameter in ObjectDetector()

#### Code
```
model = ObjectDetector(model="retinanet", num_classes=datamodule.num_classes, metrics=?)
```
Can Torchmetrics be used here? https://torchmetrics.readthedocs.io/en/latest/

**Comment by ethanwharris** [comment]
Hi @deepseek-eoghan yes, you can pass a `Metric` class to the metrics argument. See for example how the accuracy metric is added here: https://github.com/PyTorchLightning/lightning-flash/blob/447c28ee39139f5424f3726b00eb6a500394ea19/flash/core/classification.py#L43

I've openened an issue (#361) to improve the docs around metrics.

Hope that helps! :smiley:
