### ISSUE TITLE
Multilabel text classification not working

### ISSUE THREAD

**Issue by ethanwharris** [PyTorchLightning/lightning-flash#397]
## 🐛 Bug

From #395 it looks like multilabel classification doesn't work for text. We should fix this.

cc @jorgeutd

**Comment by jorgeutd** [comment]
Thank you @ethanwharris. Looking forward to leveraging this feature once that is available. Please let me know about a working example to follow on how to encode the label or to pass the string to the datamodule.

**Comment by jorgeutd** [comment]
Thank you @ethanwharris let me try this over the weekend. I really appreciate the help on this. Where I can learn more about lighting and flash for other tasks? Like model arguments or running in aws?

**Comment by ethanwharris** [comment]
@jorgeutd No problem :smiley: You could try going through our docs: https://lightning-flash.readthedocs.io/en/latest/?badge=latest They need some work so any feedback you have would be awesome!
