### ISSUE TITLE
Confusion between _PIL_AVAILABLE and _IMAGE_AVAILABLE flags

### ISSUE THREAD

**Issue by fstroth** [PyTorchLightning/lightning-flash#425]
## 🐛 Bug

In `flash.core.utilities.imports` the flag `_PIL_AVAILABLE` is defined but only used for a test (see: [link](https://github.com/PyTorchLightning/lightning-flash/search?q=_PIL_AVAILABLE))

For the import of PIL the `_IMAGE_AVAILABLE` flag is used, which is defined as `_IMAGE_AVAILABLE = _TORCHVISION_AVAILABLE and _TIMM_AVAILABLE and _KORNIA_AVAILABLE`.
The cases where `_IMAGE_AVAILABLE` is use to check for the import of PIL can be found [here](https://github.com/PyTorchLightning/lightning-flash/search?q=_IMAGE_AVAILABLE).

This causes errors for `datamodule.show_val_batch()`.

#### Code sample
```python
from flash.core.utilities.imports import _IMAGE_AVAILABLE, _module_available

print(_module_available("PIL")) # will print True if PIL is installed

print(_IMAGE_AVAILABLE) # will print False if torchvision, timm or kornia is missing
```

### Expected behavior

PIL should be imported when the _PIL_AVAILABLE is True and not the _IMAGE_AVAILABLE flag.

**Comment by ethanwharris** [comment]
Hi @fstroth thanks for reporting this bug! `_IMAGE_AVAILABLE` should be `True` if all of the image dependencies are installed (listed here: https://github.com/PyTorchLightning/lightning-flash/blob/master/requirements/datatype_image.txt) which should include Pillow. Would you be interested in opening a PR to fix this?

Thanks again :smiley:

**Comment by fstroth** [comment]
Hey @ethanwharris I have the fix done. But there are some parts were the `_IMAGE_AVAILABLE` flag is use only to import torchvision for example. Should I replace it in those cases with the `_TORCHVISION_AVAILABLE` flag?

**Comment by ethanwharris** [comment]
@fstroth awesome! I think either would be fine, so I leave it up to you :smiley:
