### ISSUE TITLE
Docs build lottery

### ISSUE THREAD

**Issue by ethanwharris** [PyTorchLightning/lightning-flash#427]
## 🐛 Bug

@ehofesmann We still seem to be getting this issue:
```
intersphinx inventory 'https://voxel51.com/docs/fiftyone/objects.inv' not fetchable due to <class 'requests.exceptions.ConnectionError'>: HTTPSConnectionPool(host='voxel51.com', port=443): Max retries exceeded with url: /docs/fiftyone/objects.inv (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5fbc2d56d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```
Example here: https://github.com/PyTorchLightning/lightning-flash/pull/426/checks?check_run_id=2860706755

Is it because we have multiple CI trying to get it at once?

I think for now we can probably try to just ignore that warning, but would be interested to know the root cause. @Borda any idea how we can ignore just a specific warning in sphinx build? Or any idea what might be causing the issue?

(Just to provide some context, we typically get the error then I re-trigger the build and it's fine)

**Comment by Borda** [comment]
is it pulling voxel51 docs or some dataset?

**Comment by ethanwharris** [comment]
@Borda It's getting the fiftyone intersphinx inv thing that seems to be the issue. So the URL configured here: https://github.com/PyTorchLightning/lightning-flash/blob/17e4a2241942cab492c95f8959cec08c1d889f21/docs/source/conf.py#L101

**Comment by ehofesmann** [comment]
We have noticed this still occurring as well and are still looking into it. It seems to be an issue with our website hosting provider that we are trying to resolve. In the meantime, handling the error when building the docs would likely the best way to avoid requiring to re-trigger the build.

**Comment by ethanwharris** [comment]
@ehofesmann Awesome, thanks for looking into it, I'll try to find a way to suppress the warning :smiley:
