### ISSUE TITLE
The serve example from the readme.md does not work

### ISSUE THREAD

**Issue by zippeurfou** [PyTorchLightning/lightning-flash#428]
## 🐛 Bug

Tried the example from the master branch after installing serve and it did not work

### To Reproduce

install flash using `pip install git+https://github.com/PytorchLightning/lightning-flash.git@master`
install serve using `pip install 'lightning-flash[serve]'`
Execute the example for the translation task:
`model = TranslationTask.load_from_checkpoint("https://flash-weights.s3.amazonaws.com/translation_model_en_ro.pt")`
Get the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/marcferradou/.pyenv/versions/grid-3.7.3/lib/python3.7/site-packages/flash/core/model.py", line 627, in serve
    raise NotImplementedError("This Task is not servable. Attach a Deserializer to enable serving.")
NotImplementedError: This Task is not servable. Attach a Deserializer to enable serving.
````
<img width="1055" alt="Screen Shot 2021-06-18 at 3 20 47 PM" src="https://user-images.githubusercontent.com/4520383/122607948-5f993c00-d049-11eb-82b4-beaba10d9cda.png">

**Comment by ethanwharris** [comment]
@zippeurfou whoops, that's a bug. Currently we don't support serve for translation, not sure how that example got there haha. Thanks for bringing it to our attention! You can see the supported examples (which should work) here: https://github.com/PyTorchLightning/lightning-flash/tree/master/flash_examples/serve

**Comment by zippeurfou** [comment]
ahaha good to know :P 
Maybe the PR should then use another example :)

**Comment by ethanwharris** [comment]
Yeah, we should switch the example in the readme to something we actually support :laughing:

**Comment by zippeurfou** [comment]
Outside of the scope of this issue but taking the first example from the doc:
https://lightning-flash.readthedocs.io/en/latest/reference/flash_to_production.html#
```
from flash.image import SemanticSegmentation
from flash.image.segmentation.serialization import SegmentationLabels

model = SemanticSegmentation.load_from_checkpoint(
    "https://flash-weights.s3.amazonaws.com/semantic_segmentation_model.pt"
)
```
It is asking for kornia as a dependency.
Should we install it by default or suggest a command how to install it (the same way you do for serve?)
<img width="1787" alt="Screen Shot 2021-06-18 at 3 40 48 PM" src="https://user-images.githubusercontent.com/4520383/122609204-9ec88c80-d04b-11eb-8a0d-3f8cb2a7fe3e.png">

**Comment by ethanwharris** [comment]
Great point! We should say that you need serve plus the deps for whichever data type you are using. So for this it would be `pip install lightning-flash[serve,image]` (I think that's how it works anyway)
