### ISSUE TITLE
FileNotFoundError running serve in clean env with 0.4.0rc0

### ISSUE THREAD

**Issue by ethanwharris** [PyTorchLightning/lightning-flash#432]
## 🐛 Bug

On 0.4.0rc0, running `ImageClassifier.serve`: `FileNotFoundError: [Errno 2] No such file or directory: '/Users/ethan/miniconda3/envs/test_env/lib/python3.8/site-packages/flash/assets/fish.jpg'`

**Comment by Borda** [comment]
you can check it locally, making `sdict` and then unzip package and see what is inside :]

**Comment by ethanwharris** [comment]
@Borda Cool! Tried it on #433 and it seems to fix it :smiley:
