### ISSUE TITLE
Video classification example from lightning-flash/flash_examples/predict/video_classification.py not works

### ISSUE THREAD

**Issue by ValentinKovalev** [PyTorchLightning/lightning-flash#439]
### To Reproduce

install flash using `pip install git+https://github.com/PytorchLightning/lightning-flash.git@master`
install pytorch video using `pip install pytorchvideo`
Execute the example for the video classification task:
# 2. Make a prediction
```python
predictions = model.predict("data/kinetics/predict/")
```
Get the error:
```
    predictions = model.predict("data/kinetics/predict/")
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flash/core/model.py", line 77, in wrapper
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flash/core/model.py", line 213, in predict
    x = [x for x in data_pipeline.data_source.generate_dataset(x, running_stage)]
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flash/core/model.py", line 213, in <listcomp>
    x = [x for x in data_pipeline.data_source.generate_dataset(x, running_stage)]
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flash/core/data/auto_dataset.py", line 96, in __getitem__
    return self._call_load_sample(self.data[index])
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flash/core/data/auto_dataset.py", line 87, in _call_load_sample
    sample = self.load_sample(sample)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flash/video/classification/data.py", line 85, in predict_load_sample
    sample.update(self._encoded_video_to_dict(EncodedVideo.from_path(video_path)))
  File "/home/ubuntu/.local/lib/python3.7/site-packages/flash/video/classification/data.py", line 96, in _encoded_video_to_dict
    ) = self.clip_sampler(0.0, video.duration)
TypeError: __call__() missing 1 required positional argument: 'annotation'
```

### Environment

 - PyTorch Version: 1.9.0+cu111
 - OS :Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): --
 - Python version: 3.7.10
 - CUDA/cuDNN version: cuda 11.1
 - GPU models and configuration:
 - Any other relevant information:

**Comment by ethanwharris** [comment]
Hi @ValentinKovalev thanks for the bug report! Currently we require `pytorchvideo==0.1.0`. Could you run `pip install pytorchvideo==0.1.0` and see if it works?

Hope that helps 😃

**Comment by ValentinKovalev** [comment]
Hi, @ethanwharris. Forgot to add, it could be a different issue:
I've renamed few imports, like `LabeledVideoDataset`, `labeled_video_dataset`, because they were renamed on `pytorchvideo`.
Reinstalled suggested version of `pytorchvideo`, and it still don't work even on `pytorchvideo==0.1.0` :(

**Comment by ethanwharris** [comment]
Hi @ValentinKovalev Can I ask how you renamed the imports? Do you mean by editing site-packages? If so, it looks like you would just need to change line 96 of `flash/video/classification/data.py` to `) = self.clip_sampler(0.0, video.duration, {})`

**Comment by ValentinKovalev** [comment]
Yep, I've changed this line in the file `flash/video/classification/data.py`
line 46: 
Before: `from pytorchvideo.data.encoded_video_dataset import EncodedVideoDataset, labeled_encoded_video_dataset`
After:`from pytorchvideo.data.encoded_video_dataset import EncodedVideoDataset, labeled_encoded_video_dataset`

And related methods names.
And yes, I lied to you :sweat_smile: @ethanwharris After reinstalling `pytorchvideo==0.1.0` and fixing methods names, example works. But it also an example required to define augmentations for the model and data, that we used. I could try to make a PR, if it is required :upside_down_face:

**Comment by ethanwharris** [comment]
@ValentinKovalev glad you got it working! PRs are always welcome :smiley:

**Comment by ValentinKovalev** [comment]
@ethanwharris, could you recommend the way, how to upload the dataset from the folder and use transforms? Couldn't find the correct way in docs. Thanks
In the tutorial I see:
`# 2. Make a prediction
predictions = model.predict("data/kinetics/predict")
print(predictions)
`
But here used clipped (== required size transforms) dataset

**Comment by ethanwharris** [comment]
Hi @ValentinKovalev sorry for the delayed reply! You can take a look at the default transforms we use here: https://github.com/PyTorchLightning/lightning-flash/blob/828fbf09a0150d795271310e7208fdf50c996bd9/flash/video/classification/data.py#L278 - you should be able to adapt that to your needs. Hope that helps!
