### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in comparison encountered while finetuning

### ISSUE THREAD

**Issue by plaban1981** [PyTorchLightning/lightning-flash#455]
### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?

Question 1 : As a part of Lightning-Flash , do you have provision to prepare datamodules from dataframe

#### Code
Like we have the from_folders
```python
datamodule = ImageClassificationData.from_folders(
    train_folder="data/hymenoptera_data/train/",
    val_folder="data/hymenoptera_data/val/",
    test_folder="data/hymenoptera_data/test/",
)
```

Question 1 : Do we have ImageClassificationData.from_dataframe() ?

Question 2 : Encounter RecursionError: while performing finetuning

```python
# 2. Load the data
datamodule = ImageClassificationData.from_folders(
    train_folder="/content/drive/MyDrive/dphi/Kvasir/The Kvasir-Capsule/TRAIN/",
    val_folder="/content/drive/MyDrive/dphi/Kvasir/The Kvasir-Capsule/VAL/",
    predict_folder="/content/drive/MyDrive/dphi/Kvasir/The Kvasir-Capsule/test/",
)

# 3 Build the model
model = ImageClassifier(backbone="densenet121", num_classes=datamodule.num_classes)

# 4. Train the model
trainer.finetune(model, datamodule=datamodule, strategy=FreezeUnfreeze(unfreeze_epoch=1))
```

Error Encountered:-
```
RecursionError: maximum recursion depth exceeded in comparison
```

#### What's your environment?
Lightning-flash version :0.4.1dev
Lightning version : 1.3.7post0
Coding in Google Colab
 - OS: [e.g. iOS, Linux, Win]
 - Packaging [e.g. pip, conda]
 - Version [e.g. 0.5.2.1]

**Comment by ethanwharris** [comment]
Hi @plaban1981 Regarding 1, we don't yet but there is an issue to add it in #257 Regarding 2, I've been able to reproduce the bug, taking a look at it now. Thanks :smiley:

**Comment by plaban1981** [comment]
Thanks  @ethanwharris  for looking into the issue. Please do let know, once the correction is freeze ; so that I could will try with finetune method again.

**Comment by ethanwharris** [comment]
Hi @plaban1981 This turned out to be an issue in lightning. The PR PyTorchLightning/lightning-flash#8170 has been merged now so your issue should be fixed when lightning 1.3.8 is released (should be tomorrow). Hope that helps :smiley:

**Comment by plaban1981** [comment]
Thank You @ethanwharris .Much Appreciated!!!

**Comment by ethanwharris** [comment]
1.3.8 is out so this should now be resolved :smiley: Feel free to re-open if not
