### ISSUE TITLE
Additional Visualizations for the datamodules

### ISSUE THREAD

**Issue by fstroth** [PyTorchLightning/lightning-flash#456]
## 🚀 Feature
I would like to add some visualizations to the task specific datamodules. For example for the classifications tasks a histogram of the occurrences for each class.

### Motivation

The plots would be of interest from an exploratory standpoint if one reads in new data with a data module and than wants to refine the dataset. As for real world datasets one often has to create plots of different distributions for the dataset to look for skewness in the class distribution and many other things. Furthermore, when someone uses a data source prepared by someone else it would be an easy way to get some insight into a dataset.

### Pitch

Extend the datamodule with plotting functions that are specific to the different tasks. This could be done as plotting functions implemented in each datamodule definition or as a separate class which is a mixin for the datamodules. 

### Additional context

I would like to discuss if that feature would be of interest and what would be the best way to go about it. Once a conclusion is reached I can implement it than.

**Comment by tchaton** [comment]
Dear @fstroth,

You can built your visualization using BaseVisualization Callback. Check out this code: https://github.com/PyTorchLightning/lightning-flash/blob/master/flash/image/classification/data.py#L106

Best,
T.C
