### ISSUE TITLE
Document `ObjectDetectionData` transforms

### ISSUE THREAD

**Issue by ethanwharris** [PyTorchLightning/lightning-flash#488]
## 📚 Documentation

It is possible (although not trivial) to get bounding box augmentations / transforms working with `ObjectDetectionData` (see #414). We should document this somewhere, ideally providing some examples.

cc @hzitoun

**Comment by gianscarpe** [comment]
Hi @ethanwharris , I've experience working with object-detection and data-augmentation through albumentatations. If it's still needed I start working on the issue :)

**Comment by ethanwharris** [comment]
Hi @gianscarpe, some documentation here would definitely be welcome :smiley: Our object detection now relies on IceVision underneath so our support for albumentations is much better than it used to be. You should now be able to wrap albumentations augmentations in the `IceVisionTransformAdapter` (maybe the name `AlbumentationsAdapter` or something would be better?) here: https://github.com/PyTorchLightning/lightning-flash/blob/cf86275d629092e4c43f2d996061bff7abe17784/flash/core/integrations/icevision/transforms.py#L198

There's a couple of examples further down that page where we use the default transforms from IceVision. It would be very welcome for you to add a documentation section about this similar to what we have for image classification here: https://lightning-flash.readthedocs.io/en/latest/reference/image_classification.html#custom-transformations

Thanks for your help :smiley:

**Comment by gianscarpe** [comment]
Hi @ethanwharris, I'd like to discuss a feature that maybe it's missing. Let me know if a new issue is more appropriate. 
Detectron2 library allows to evaluate a model using the standard COCO evaluator by wrapping it inside an evaluator function. I find this feature extremely compelling, especially since evaluator object-detector is not trivial. Do you plan to add similar features to flash?

**Comment by ethanwharris** [comment]
Hi @gianscarpe in theory we should now support this, but it would be great for you to try i out and maybe update the documentation there if you're interested. The way it should work is that you can pass a metric from Icevision to the ObjectDetector task. Here's some code that _should_ be working:
```
from icevision.metrics import COCOMetric, COCOMetricType

model = ObjectDetector(..., metrics=[COCOMetric(COCOMetricType.bbox)])
```

Let me know if that works and how the experience there could be improved! :smiley:
