### ISSUE TITLE
Remove unused `Preprocess`'s methods for data saving

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/lightning-flash#494]
## 🚀 Refactoring
Unless there is any plan to utilise the following lines in the near future, they should be removed from the codebase.

https://github.com/PyTorchLightning/lightning-flash/blob/d0e6ee65419e140ea7894f1c03a5955919d66310/flash/core/data/process.py#L501-L511

**Comment by ethanwharris** [comment]
@akihironitta Yeah, I think they can probably be removed. @tchaton any idea what these are for?
