### ISSUE TITLE
Improve or remove the docs for `FlashCallback`

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/lightning-flash#495]
## 📚 Documentation
Currently, the doc says almost nothing about what new hooks are added to the original PL `Callback`.

1. Remove the doc if the class `FlashCallback` itself shouldn't be used directly by users (and should be used only internally), or
2. improve it by describing the differences between `FlashCallback` and PL's `Callback`, when they get executed, ...

---
current doc: https://lightning-flash.readthedocs.io/en/latest/general/callback.html
current code: https://github.com/PyTorchLightning/lightning-flash/blob/d0e6ee65419e140ea7894f1c03a5955919d66310/flash/core/data/callback.py

**Comment by ethanwharris** [comment]
Yeah, AFAIK these are only used for visualizing data. This is currently only discussed in the API reference, I guess it would be good to remove the callback docs and have something there for visualizing instead.
