### ISSUE TITLE
Support for `ImageClassificationData.from_list`

### ISSUE THREAD

**Issue by aniketmaurya** [PyTorchLightning/lightning-flash#499]
## 🚀 Feature

```python
image_data = [ ('path1', 'CLASS-A'), ('path2', 'CLASS-A'), ('path3', 'CLASS-B'), ...]

datamodule = ImageClassificationData.from_list(
    train_list =image_data,
    train_transform=transform,)
```
### Motivation

Mostly the dataset is not structured in a good manner and it is very irritating to write custom `Dataset`. So having this method can help a lot.

### Pitch
I would like to have this method in Flash. 

### Additional context

Will be happy to contribute to this ⚡️ 💜

**Comment by ethanwharris** [comment]
Hi @aniketmaurya, how does this compare to `from_files`? With that you can do:
```
ImageClassificatiomData.from_files(
    train_files = ["image_1.png", "image_2.png", ...],
    train_targets = [0, 1, ...],
)
```
Does that do what you need?

**Comment by aniketmaurya** [comment]
Yes  yes @ethanwharris , this is what I need

**Comment by ethanwharris** [comment]
@aniketmaurya Great :smiley: closing this
