### ISSUE TITLE
Modify SEMANTIC_SEGMENTATION_HEADS and SEMANTIC_SEGMENTATION_BACKBONES registries to work with segmentation_models.pytorch

### ISSUE THREAD

**Issue by ethanwharris** [PyTorchLightning/lightning-flash#515]

**Comment by aniketmaurya** [comment]
hi @ethanwharris , will we keep the existing Bolts and torchvision models after this integration? Or can I remove these?

**Comment by ethanwharris** [comment]
Hi @aniketmaurya you can remove them as they should be covered by segmentation_models.pytorch :smiley:
