### ISSUE TITLE
Create QuestionAnsweringPreprocess based on SummarizationPreprocess

### ISSUE THREAD

**Issue by ethanwharris** [PyTorchLightning/lightning-flash#536]

**Comment by karthikrangasai** [comment]
@ethanwharris 
What is the backbone model I must use ?

**Comment by ethanwharris** [comment]
Hi @karthikrangasai the backbone should be a variable passed to the init as with our other seq2seq tasks. It should have a default which can be anything you like (although preferably something pretrained for question answering and not too big).

Hope that helps :smiley:

**Comment by karthikrangasai** [comment]
@ethanwharris 
I wanted a specific model name, but it is nice that I get to choose 😄

**Comment by ethanwharris** [comment]
Fixed by #565
