### ISSUE TITLE
Add an AUDIO_SOURCE_SEPARATION_BACKBONES FlashRegistry with a few simple models from Asteroid

### ISSUE THREAD

**Issue by ethanwharris** [PyTorchLightning/lightning-flash#548]

**Comment by saswatpp** [comment]
Hello. So I've been seeing some examples to understand how to register the models in the `AUDIO_SOURCE_SEPARATION_BACKBONES`. So what all models do I need to add in the registry ? The following has the list of models :  https://github.com/asteroid-team/asteroid/tree/master/asteroid/models 

So as I understand, I will have to add the following files right ? : lightning-flash/flash/audio/source_separation/backbones.py. Could anyone guide me ?

**Comment by saswatpp** [comment]
Hello. So I've been seeing some examples to understand how to register the models in the `AUDIO_SOURCE_SEPARATION_BACKBONES`. So what all models do I need to add in the registry ? The following has the list of models :  https://github.com/asteroid-team/asteroid/tree/master/asteroid/models 

So as I understand, I will have to add the following files right ? : `lightning-flash/flash/audio/source_separation/backbones.py`. Could anyone guide me ?

**Comment by saswatpp** [comment]
yes I got it @ethanwharris. Moreover, 
Can you suggest any previous previous `backbone.py` file that imports the models (similar to `asteroid.models` scenario). All the `backbone.py` files seems specialized for the library-to-be-integrated and I am a little confused so as to how to add them.
