### ISSUE TITLE
Add an audio_source_separation example

### ISSUE THREAD

**Issue by ethanwharris** [PyTorchLightning/lightning-flash#550]

**Comment by hihunjin** [comment]
Hello.
I've found that you install some more modules/apis like [link](https://github.com/PyTorchLightning/lightning-flash/blob/master/flash/core/utilities/imports.py#L106-L129).
Should we also write down the things like that and pr it?

**Comment by hihunjin** [comment]
And please assign this issue to me (if it's possible).

**Comment by ethanwharris** [comment]
Hi @hihunjin, yes I forgot to mention that! You will need to add some dependency management. It can be a bit tricky so please reach out for help if you need :smiley:
