### ISSUE TITLE
ObjectDetector: predict on numpy array fails

### ISSUE THREAD

**Issue by hzitoun** [PyTorchLightning/lightning-flash#569]
## 🐛 Bug

The `mode.predict` method only works with image file path. When using the method with a numpy array I got:

```
/usr/lib/python3.7/genericpath.py in isdir(s)
     40     """Return true if the pathname refers to an existing directory."""
     41     try:
---> 42         st = os.stat(s)
     43     except OSError:
     44         return False

ValueError: stat: embedded null character in path
```

### To Reproduce

```python
import PIL
import numpy as np

img_pil = PIL.Image.open('image.jpg')

predict_data = np.array(img_pil)

model = ObjectDetector.load_from_checkpoint("model.pt")

predictions = model.predict(predict_data) #  model.predict([predict_data]) fails also

```

### Expected behavior

Being able to predict using a numpy array! 

### Environment

 - PyTorch Version: 1.9.0+cu102
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): pip install 
 - Python version: 3.8
 - CUDA/cuDNN version: 11

**Comment by hzitoun** [comment]
cc @ethanwharris

**Comment by ethanwharris** [comment]
Hi @hzitoun looks like we don't currently have a NumpyDataSource configured for object detection so it's not currently supported. It would be reasonably easy to add the ImageNumpyDataSource to the ObjectDetectionPreprocess. Then you would be able to do:
```
model.predict(my_numpy_array, data_source="numpy")
```

We don't currently have any way to do type inference on the input to predict so you would still have to specify that you have numpy data. Would you be interested in making a PR to add the ImageNumpyDataSource here?https://github.com/PyTorchLightning/lightning-flash/blob/bf1526fa1395f80a4bc722ddc6f476427f9c9a60/flash/image/detection/data.py#L193
