### ISSUE TITLE
Change the function name `test_jit` in tests/text to `test_compatibility_with_jit`

### ISSUE THREAD

**Issue by karthikrangasai** [PyTorchLightning/lightning-flash#570]
The current name for method used to test the compatibility of text models with TorchScript is names `test_jit` which could renamed to a descriptive name like `test_compatibility_with_jit`. 

I am willing to submit a PR for this issue as well.

**Comment by ananyahjha93** [comment]
I think ```test_jit``` is fine but I'll leave it up to @ethanwharris  or @tchaton to decide if we want to rename this function.

**Comment by ethanwharris** [comment]
@ananyahjha93 the name suggestion came from @Borda happy to havw some kind of vote or something here haha
