### ISSUE TITLE
Inconsistent structure in submodules

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/lightning-flash#578]
## 🐛 Bug
Some `Preprocess`es are unavailable right under `flash.image`. Haven't checked, but there could be more at other domains, such as `flash.{text,tabular,video,...}`.

```python
from flash.image import ImageClassificationPreprocess  # succeeds
from flash.image import ObjectDetectionPreprocess  # fails
from flash.image.detection.data import ObjectDetectionPreprocess  # succeeds
```

### To Reproduce

```python
>>> from flash.image import ImageClassificationPreprocess
>>> from flash.image import ObjectDetectionPreprocess
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ObjectDetectionPreprocess' from 'flash.image' (/home/nitta/work/github.com/PyTorchLightning/lightning-flash/flash/image/__init__.py)
```

### Expected behavior
For consistency, both of the following lines should be run successfully or should throw `ModuleNotFoundError`.
```python
from flash.image import ImageClassificationPreprocess
from flash.image import ObjectDetectionPreprocess
```

### Environment

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

### Additional context

**Comment by ethanwharris** [comment]
HI @akihironitta yeah, this is quite inconsistent. I would vote for having all Preprocess objects not be exposed to the user through the data type. If they want to access the preprocess class for some reason a full import would suffice. I think some of them were made available to the user a while back but not really needed anymore.

**Comment by akihironitta** [comment]
@ethanwharris Sounds good :] How about this one? Flash currently allows users to import, for example, `ImageClassifier` in the following ways. One in the middle doesn't look good to me because it gives users too many options to import a single name and it may be confusing IMHO.

```python
from flash.image import ImageClassifier  # expose tasks via data type
from flash.image.classification import ImageClassifier  # Should we allow this?
from flash.image.classification.model import ImageClassifier  # (importing with a full path)
```
