### ISSUE TITLE
Installation Issues: Can't Run Audio Classification Example

### ISSUE THREAD

**Issue by luiscape** [PyTorchLightning/lightning-flash#624]
## 🐛 Bug

When attempting to run the audio classification from the documentation [here](https://lightning-flash.readthedocs.io/en/latest/reference/audio_classification.html), I'm hit with an import error. This prevents me from running the example. I am trying to run the example as is without any modifications.

Error:

```shell
(venv) ¬ python example.py
/Users/luiscape/programs/audity/venv/lib/python3.8/site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
Uncaught exception
Traceback (most recent call last):
  File "example.py", line 2, in <module>
    from flash.audio import AudioClassificationData
ModuleNotFoundError: No module named 'flash.audio'
```

### To Reproduce

1. Create virtual env: `python3 -m venv venv && source venv/bin/activate`
2. Install Flash with `pip install 'lightning-flash[all]'`
2. Copy example from [documentation page](https://lightning-flash.readthedocs.io/en/latest/reference/audio_classification.html) into `example.py` script
3. Run example with `python example.py`

### Environment

 - PyTorch Version (e.g., 1.0): `1.9.0`
 - OS (e.g., Linux): `macOS 11.4`
 - How you installed PyTorch (`conda`, `pip`, source): `pip`
 - Python version: `Python 3.8.6`

**Comment by ethanwharris** [comment]
Hi @luiscape, I think the issue is that the audio task hasn't been included in a release yet. Could you try installing with:
```
pip install 'git+https://github.com/PyTorchLightning/lightning-flash.git#egg=lightning-flash[audio]'
```

Hope that helps :smiley:

**Comment by luiscape** [comment]
Yeah, that worked. Thank you.

Maybe the real issue here is that the latest docs refer to an unreleased version? That was a bit confusing to me.

I'll close the issue because you resolved the original prompt. Should I open a new one re the docs or not an issue?
