### ISSUE TITLE
Cannot tune Object Detection example

### ISSUE THREAD

**Issue by twsl** [PyTorchLightning/lightning-flash#636]
### To Reproduce

1. Use the example code for Object Detection from the README
2. replace step 4 with the following code:
```
trainer = flash.Trainer(max_epochs=3, auto_scale_batch_size=True, gpus=[1])
trainer.tune(model)
```
3. See error

```
MisconfigurationException: Field batch_size not found in both `model` and `model.hparams`
```
<details>
<summary>Full exception</summary>

```
---------------------------------------------------------------------------
MisconfigurationException                 Traceback (most recent call last)
<command-3161924859406588> in <module>
     19 # 4. Create the trainer. Run twice on data
     20 trainer = flash.Trainer(max_epochs=3, auto_scale_batch_size=True, gpus=[1])
---> 21 trainer.tune(model)
     22 
     23 # 5. Finetune the model

/databricks/python/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py in tune(self, model, train_dataloaders, val_dataloaders, datamodule, scale_batch_size_kwargs, lr_find_kwargs, train_dataloader)
    836         )
    837 
--> 838         result = self.tuner._tune(model, scale_batch_size_kwargs=scale_batch_size_kwargs, lr_find_kwargs=lr_find_kwargs)
    839 
    840         assert self.state.stopped

/databricks/python/lib/python3.8/site-packages/pytorch_lightning/tuner/tuning.py in _tune(self, model, scale_batch_size_kwargs, lr_find_kwargs)
     46             if isinstance(self.trainer.auto_scale_batch_size, str):
     47                 scale_batch_size_kwargs.setdefault("mode", self.trainer.auto_scale_batch_size)
---> 48             result["scale_batch_size"] = scale_batch_size(self.trainer, model, **scale_batch_size_kwargs)
     49 
     50         # Run learning rate finder:

/databricks/python/lib/python3.8/site-packages/pytorch_lightning/tuner/batch_size_scaling.py in scale_batch_size(trainer, model, mode, steps_per_trial, init_val, max_trials, batch_arg_name)
     43 
     44     if not lightning_hasattr(model, batch_arg_name):
---> 45         raise MisconfigurationException(f"Field {batch_arg_name} not found in both `model` and `model.hparams`")
     46     if hasattr(model, batch_arg_name) and hasattr(model, "hparams") and batch_arg_name in model.hparams:
     47         rank_zero_warn(

MisconfigurationException: Field batch_size not found in both `model` and `model.hparams`
```

</details>

### Expected behavior

A simple batch size tuning.

### Environment

 - PyTorch Version (e.g., 1.0): 1.9.0+cu102
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): -
 - Python version: 3.8.8
 - CUDA/cuDNN version: 11.0
 - GPU models and configuration: 2x NVIDIA Tesla K80
 - Any other relevant information:

**Comment by aribornstein** [comment]
Does this work if you don't try to autoscale the batch size?

@ethanwharris

**Comment by ethanwharris** [comment]
Hi @twsl I think this is a limitation of the batch size autoscaler. From the docs - https://pytorch-lightning.readthedocs.io/en/latest/advanced/training_tricks.html#auto-scaling-of-batch-size - the feature doesn't work when passing the dataloaders / datamodule directly to the trainer fit / finetune call. I think the best course of action would be to add support on the lightning side to pass in a datamodule rather than just using a batch_size attribute on the model. I've opened an issue here: https://github.com/PyTorchLightning/pytorch-lightning/issues/8753

Hope that helps :smiley:

**Comment by twsl** [comment]
Given the fact that the minimal example in the linked issue works, it might be an issue in lightning-flash, right?

**Comment by ethanwharris** [comment]
@twsl it looks lile you should be able to get it working with:
```
data_module = ObjectDetectionData(...)
model = ObjectDetector(...)
trainer = flash.Trainer(...)
trainer.tune(model, data_module)
```

Hope that helps :smiley:

**Comment by twsl** [comment]
This is probably a seperated issue, but calling the example code with `flash.Trainer(...,gpus=-1, accelerator='dp')` causes an exception: `RuntimeError: chunk expects at least a 1-dimensional tensor`. Calling on a sinlge GPU works.
