### ISSUE TITLE
TypeError: list indices must be integers or slices, not DefaultDataKey

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [PyTorchLightning/lightning-flash#637]
## 🐛 Bug

Hi guys, flash seems to expect data loaders to return dictionaries and not normal tuples  like in 99% of the cases

### To Reproduce

Steps to reproduce the behavior. Just run the sample code

```

(venv) zuppif@blackbird:~/gust-torchvision$ /home/zuppif/gust-torchvision/venv/bin/python3 /home/zuppif/gust-torchvision/playground.py
eehh
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]
Traceback (most recent call last):
  File "/home/zuppif/gust-torchvision/playground.py", line 60, in <module>
    trainer.finetune(classifier, datamodule=dm, strategy="freeze")
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/flash/core/trainer.py", line 165, in finetune
    return super().fit(model, train_dataloader, val_dataloaders, datamodule)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in fit
    self._run(model)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 912, in _run
    self._pre_dispatch()
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 941, in _pre_dispatch
    self._log_hyperparams()
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 970, in _log_hyperparams
    self.logger.save()
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py", line 48, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/loggers/tensorboard.py", line 249, in save
    save_hparams_to_yaml(hparams_file, self.hparams)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 413, in save_hparams_to_yaml
    with fs.open(config_yaml, "w", newline="") as fp:
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fsspec/spec.py", line 972, in open
    self.open(path, mode, block_size, **kwargs), **text_kwargs
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fsspec/spec.py", line 976, in open
    f = self._open(
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fsspec/implementations/local.py", line 145, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fsspec/implementations/local.py", line 236, in __init__
    self._open()
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/fsspec/implementations/local.py", line 241, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/zuppif/gust-torchvision/lightning_logs/version_2/hparams.yaml'
(venv) zuppif@blackbird:~/gust-torchvision$ /home/zuppif/gust-torchvision/venv/bin/python3 /home/zuppif/gust-torchvision/playground.py
eehh
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2]

  | Name          | Type       | Params
---------------------------------------------
0 | train_metrics | ModuleDict | 0     
1 | val_metrics   | ModuleDict | 0     
2 | backbone      | Sequential | 11.2 M
3 | head          | Sequential | 5.1 K 
---------------------------------------------
14.7 K    Trainable params
11.2 M    Non-trainable params
11.2 M    Total params
44.727    Total estimated model params size (MB)
Validation sanity check: 0it [00:00, ?it/s]/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/flash/core/model.py:397: LightningDeprecationWarning: The `LightningModule.datamodule` property is deprecated in v1.3 and will be removed in v1.5. Access the datamodule through using `self.trainer.datamodule` instead.
  if self.datamodule is not None and getattr(self.datamodule, "data_pipeline", None) is not None:
Validation sanity check:   0%|                                                                                                                                      | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/zuppif/gust-torchvision/playground.py", line 60, in <module>
    trainer.finetune(classifier, datamodule=dm, strategy="freeze")
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/flash/core/trainer.py", line 165, in finetune
    return super().fit(model, train_dataloader, val_dataloaders, datamodule)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in fit
    self._run(model)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 918, in _run
    self._dispatch()
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 986, in _dispatch
    self.accelerator.start_training(self)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 996, in run_stage
    return self._run_train()
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1031, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/flash/core/trainer.py", line 93, in _run_sanity_check
    super()._run_sanity_check(ref_model)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1115, in _run_sanity_check
    self._evaluation_loop.run()
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 110, in advance
    output = self.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 154, in evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 211, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 178, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/zuppif/gust-torchvision/venv/lib/python3.8/site-packages/flash/image/classification/model.py", line 121, in validation_step
    batch = (batch[DefaultDataKeys.INPUT], batch[DefaultDataKeys.TARGET])
TypeError: list indices must be integers or slices, not DefaultDataKeys
(venv) zuppif@blackbird:~/gust-torchvision$ 
```

#### Code sample

```python
class FakeData(LightningDataModule):

    def __init__(self, n: int = 512, n_classes: int = 10):
        super().__init__()
        self.n = n
        self.n_classes = n_classes

    def dataloader(self):
        imgs, labels = torch.randn((self.n, 3, 224, 224)), torch.randint(0, self.n_classes, size=(self.n, 1))
        ds = TensorDataset(imgs, labels)
        return DataLoader(ds, batch_size=32, num_workers=8)

    def train_dataloader(self):
        return self.dataloader()

    def val_dataloader(self):
        return self.dataloader()

    def test_dataloader(self):
        return self.dataloader()

dm = FakeData()

dl = dm.train_dataloader()
num_classes = dm.n_classes

metrics = M.MetricCollection({
    'accuracy': M.Accuracy(num_classes=num_classes),
    'recall': M.Recall(num_classes=num_classes),
    'f1': M.F1(num_classes=num_classes),
    'precision': M.Precision(num_classes=num_classes)
})

classifier = ImageClassifier(backbone='resnet18', num_classes=dm.n_classes, metrics=metrics)

trainer = Trainer(gpus=1, max_epochs=1)
trainer.finetune(classifier, datamodule=dm, strategy="freeze")

trainer.save_checkpoint('./checkpoint.pt')
```

### Expected behavior

It should work

### Environment

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by FrancescoSaverioZuppichini** [comment]
Even using your `from flash.core.data.data_module import DataModule` does not work

```python
dm = DataModule(
    TensorDataset(torch.randn((512, 3, 224, 224)), torch.randint(0, 10, size=(512, 1))),
    val_split=0.1,
    batch_size=32,
    num_workers=8
)

```

I don't see how this library can make prototyping faster, I've used it for 4 hours and I've found only bugs. I believe you should strongly reconsider the misleading advertisement you are making.

Thanks,

Francesco

**Comment by ethanwharris** [comment]
Hi Francesco, sorry that your experience hasn't been positive. The correct way to load the data would be using the `from_datasets` method. So you would do:
```
from flash.image import ImageClassificationData

data_module = ImageClassificationData.from_datasets(train_dataset=..., ...)
```

It is true that flash expects the datamodule to return dictionaries, but that is handled automatically by the `from_datasets` method.

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @ethanwharris , thank you for your quick response. I see, I was not aware of this method. btw, in your doc (https://lightning-flash.readthedocs.io/en/latest/reference/image_classification.html#example) `from_datasets` is not covered, I can PR it if you think is a nice addition. 

My code snippet comes from me trying to use flash with custom (in this case fake) data. I am evaluating if it is a good fit for my daily work :)

**Comment by ethanwharris** [comment]
Hi @FrancescoSaverioZuppichini yeah, our documentation for possible data sources is definitely lacking, we would welcome any PRs that make it better :smiley:

> So, I don't get it. **Is it possible to organize my data pipeline with `LightningDataModule` and use `flash`?**

It is poissible to do this if you want, but your data would need to be in the format that the `ImageClassifier` task is expecting. In this case it needs dictionaries with an "input" key which maps to the image tensor and a "target" key which maps to the target tensor (this is another area where our docs are lacking). That should enable your datamodule to work directly with the image classifier task. If you use the from_datasets method instead then that creates the ImageClassificationData which includes some default augmentations (random flip, resizing, normalization etc.).

**Comment by FrancescoSaverioZuppichini** [comment]
Sure :) That makes sense! But, for better customization, would it make more sense to pass over something like `batch_extractor_strategy` what in the default case is just `lambda x: x['input'],x['target']`. That should make it easier to add new datasets or just make mine compatible to flash. 

So, just to check if I got everything right, `ImageClassificationData` is a subclass of `LightningModule`. So, is it sufficient to create a `LightningModule` and I make sure my dataset returns a dict with the right key/pair?

**Comment by ethanwharris** [comment]
> would it make more sense to pass over something like `batch_extractor_strategy` what in the default case is just `lambda x: x['input'],x['target']`. That should make it easier to add new datasets or just make mine compatible to flash.

That's a nice idea, definitely something we could look at :smiley:

> So, just to check if I got everything right, `ImageClassificationData` is a subclass of `LightningModule`. So, is it sufficient to create a `LightningModule` and I make sure my dataset returns a dict with the right key/pair?

`ImageClassificationData` is a lightning `DataModule` but with some default augmentations for images. If you have a custom datamodule where the datasets return the right key/pair then that that should work :smiley: Otherwise, if you use the `ImageClassificationData.from_datasets` method, then that has some logic to convert samples to dictionaries if they are provided as tuples.

Hope that helps :smiley:

**Comment by FrancescoSaverioZuppichini** [comment]
Hey @ethanwharris I hope you had a great weekend! Thank you again for all the help

> ImageClassificationData is a lightning DataModule

Yeah sorry :)

I will try and let you know ;)

**Comment by FrancescoSaverioZuppichini** [comment]
Honestly, I think I will just write a normal `DataModule` and `Module` from `lighting`, I get that `flash` is suppose to help but in reality, is slowing me down a lot. For example, image the following code

```python

dm = ImageClassificationData.from_datasets(
    train_dataset=ds,
)
```

What if I want to pass my own train_transform? Well I can do

```python
dm = ImageClassificationData.from_datasets(
    train_dataset=ds,
    train_transform=T.Compose(
        [
            T.Resize((256, 256)),
            T.RandomCrop((224, 224)),
            T.RandomHorizontalFlip(),
            T.RandomVerticalFlip(),
            T.ToTensor(),
        ]
    )
    )
```

**Wrong!** That must be a dict of [str, Callable], but why? After more digging, there is something called preprocess that in a container of all the transforms you need and you can also pass arguments to it from the constructor, so wait, I can pass some sort of dictionary of transformation and also parameters to this preprocess that should bundle all my transformation together. Suddenly, there isn't a way to predict the correct flow from the external APIs and I have to go through the source code that something, even if very well written, is over complicated. Sorry to say but I will remove flash, maybe it works only using the snippet in the README, but for real-life scenarios, you will spend more time reading the source code than doing the same think by yourself.

**Comment by ethanwharris** [comment]
Hi @FrancescoSaverioZuppichini Thanks for your feedback on flash. We are aware of usability issues regarding custom transforms and are working on ways to better document these (e.g. see the PR here: https://github.com/PyTorchLightning/lightning-flash/pull/620) and also to just generally improve the process. If you have any specific requests regarding an API you'd like to see, I would ask that you open some issues and start some discussions as we are usually able to implement most things pretty quickly.

**Comment by FrancescoSaverioZuppichini** [comment]
I know this is not a trivial task, but put yourself in my shoes. Your advertisement is misleading, 

> Flash is a framework of tasks for fast prototyping, baselining, finetuning and solving business and scientific problems with deep learning. It is focused on:
> 
> Predictions
> Finetuning
> Task-based training
>
> It is built for data scientists, machine learning practitioners, and applied researchers.

Just place somewhere that this is a heavy work in progress project and expect the doc to be lacking and the APIs to be misleading, nobody will ever come here and criticize your work. But if I believe this project is what you say it is and then it is so hard to use and I waste a lot of time because the codebase is still in "beta", then yeah people will be slightly pissed even if it is not fair

**Comment by tchaton** [comment]
Dear @FrancescoSaverioZuppichini,

Thanks for sharing your feedbacks !
Flash is opinionated and provide all the components to have production ready models with minimal amount of code.
Flash is not really meant for you to pass your datasets as they don't necessary full-fill the contract the contract to be production ready.

Instead

```py
dm = ImageClassificationData.from_folders(
    train_folder="data/train",
    train_transform={
        "pre_tensor_transform": T.Compose(
            [
                T.Resize((256, 256)),
            ]
        ),
        "post_tensor_transform": T.Compose(
            [
                T.RandomCrop((224, 224)),
                T.RandomHorizontalFlip(),
                T.RandomVerticalFlip(),
            ]
        )
    },
)
```

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @tchaton thank you for your fast reply and the code snippet! After the amazing discussion with @ethanwharris I used `flash` build in class method to create `ImageClassificationData` but, still, errors. If solving a task as easy as image classification requires such a deep knowledge of the code base then I believe the goal of `flash` is not reached, at least yet, and I'll drop it since I need something that I can use in production. I will use vanilla lighting as I am used to :) 

Thank you guys for all the help!

**Comment by ethanwharris** [comment]
Hi @FrancescoSaverioZuppichini I've opened a couple of issues around the experience of transforms in Flash (#644 and #645). Would be great to get your thoughts on these if you have time. We'd definitely welcome any PRs that improve the documentation!

Thanks :smiley:

**Comment by FrancescoSaverioZuppichini** [comment]
That's amazing, thank you guys :)

**Comment by rbavery** [comment]
Should this issue be closed? I'm still getting errors with tuples for image classification

> I agree, but if I see something called ImageClassificationData, so for image classification, I'll assume I need to have a (x,y) pair returned (as usual). It's a little weird to have to return a dictionary, but that's okay.
> 
> Yeah, it comes from us trying to standardise the way data is passed around within flash as much as possible. I think we can definitely relax this within the task so that it will still work with the tuple data (and then only use the dictionary format within our datamodules).

**Comment by ethanwharris** [comment]
Hey @rbavery At the moment, the input to the `ImageClassifier` is expected to be a dictionary with an "input" key and a "target" key. I think it would be valuable for us to support more conventional formats (e.g. tuples) as well, could you open a new issue to discuss this further?

Thanks 😃
