### ISSUE TITLE
Readme and example proposes to use custom embedding size for ImageEmbedder, but that is invalid according to the code warnings

### ISSUE THREAD

**Issue by tszumowski** [PyTorchLightning/lightning-flash#653]
The Embedding example in the README has the following line:
```
# 2. Create an ImageEmbedder with resnet50 trained on imagenet.
embedder = ImageEmbedder(backbone="resnet50", embedding_dim=128)
```

However, the code generates this warning when providing that `embedding_dim` field:
https://github.com/PyTorchLightning/lightning-flash/blob/4ebb0877f3d406919fc07791369f0a33643c1ec5/flash/image/embedding/model.py#L92

That can provide a new user the wrong impression that an embedder is ready for use off-the-shelf while supplying `embedding_dim`, when in fact it requires additional tuning. 

My suggestion would be to remove that `embedding_dim`, so that it reads: 
```
embedder = ImageEmbedder(backbone="resnet50")
```
Alternately, a comment can be added in the code snippet to reflect that warning as well.

Since this is a proposal, I won't PR yet. If the proposal makes sense, I can PR it in.

**Comment by tszumowski** [comment]
I also just noticed it's in this example too:
https://github.com/PyTorchLightning/lightning-flash/blob/master/flash_examples/integrations/fiftyone/image_embedding.py

https://github.com/PyTorchLightning/lightning-flash/blob/ddd942d3dfe3884a97a855446410166c3c9f16d9/flash_examples/integrations/fiftyone/image_embedding.py#L30-L35

It generates embeddings without fine tuning. This would mean a `nn.Linear` layer is placed in the head which has presumably random weights, I believe?

**Comment by ethanwharris** [comment]
Hi @tszumowski, thanks for reporting this :smiley: Definitely happy to have the `embedding_dim` argument removed. It's odd to me that the option is even there as I don't know what fientuning an embedding would look like. There's some ongoing work that _might_ clean all of this up (cc @ananyahjha93). In the meantime, I look forward to your PR!

**Comment by tszumowski** [comment]
> In the meantime, I look forward to your PR!
@ethanwharris thanks for the feedback. I opened #655. 

>  It's odd to me that the option is even there as I don't know what finetuning an embedding would look like.
Perhaps it can be used to fine-tune for a specific domain. For example, add an embedding layer, followed by a final classsification layer, and fine-tuning a pre-trained model with that head. This could be useful in some cases. 

For example, a pretrained resnet as-is can do reasonably well for visual similarity. That's how the example is written. In that case, the final layer before classification is used as the embeddings. 

However, you can also instead attach say a 64-dimension linear layer on top of that, followed by a classification layer for your domain. For example, suppose I want to classify dogs vs. cats. Something to the effect of:
```
            self.head = nn.Sequential(
                nn.Flatten(),
                nn.Linear(num_features, embedding_dim),   # the embedding layer
                nn.Linear(embedding_dim, num_classes)    # temporary classification: "dogs vs. cats"
            )
```

Then given that head, you can fine-tune to get some weights for that embedding layer. Then for embedding purposes, chop off the temporary classification layer to result in an embedding layer of size `embedding_dim`. 

That all _seems_ reasonable, I think. But I would say it seems out-of-scope for a quick example of using an Embedder.

**Comment by ethanwharris** [comment]
@tszumowski I agree with your use case there, but I would say that the correct way to acheive that is through the `ImageClassifier` rather than the `ImageEmbedder`. The `ImageEmbedder` is really just a convenience class for getting embeddings from a pre-trained model and doesn't have any facility for e.g. finetuning on a classification task. I think in an ideal world we would just have a way of generating embeddings from an `ImageClassifier` (or converting one to an `ImageEmbedder`) rather than viewing the `ImageEmbedder` as a task in it's own right. Alternatively we could implement methods for dimensionality reduction there so that finetuning corresponds to learning a layer of `embedding_dim` size that represents e.g. the principle components of the previous layer.

**Comment by tszumowski** [comment]
@ethanwharris Great points. I agree. Performing this as part of the `ImageClassifier` makes sense. For my own little studies, that's the direction I ended up going when experimenting. I did have to drop it to pivot to another task though unfortunately. 

Let's close this issue since there's no specific action that needs to be taken from it. Thanks for the clarifications and brainstorm!
