### ISSUE TITLE
Custom task with a model that happens to be a TorchLightning module fails

### ISSUE THREAD

**Issue by dlangerm** [PyTorchLightning/lightning-flash#654]
## 🐛 Bug

Building a custom task with a model that is an instance of LightningModule causes an initialization error because self._children is not initialized

### To Reproduce

1. Create a task where the model passed into the super constructor is some kind of basic torch lightning model
2. initialize the class
2. Observe the following
```
Traceback (most recent call last):
  File ".\dummy_run.py", line 29, in <module>
    train(_cfg_)
  File "xxx\train.py", line 101, in train
    net = SegmentationTask(cfg)
  File "xxx\lightning\SegmentationTask.py", line 53, in __init__
    super().__init__(
  File "xxx\envs\torch\lib\site-packages\flash\core\model.py", line 135, in __init__
    self.model = model
  File "xxx\anaconda3\envs\torch\lib\site-packages\flash\core\model.py", line 167, in __setattr__
    self._children.append(key)
  File "xxx\anaconda3\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 1130, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'SegmentationTask' object has no attribute '_children'
```

#### Code sample

```python
import flash
from flash.image import SemanticSegmentation

class SegmentationTask(flash.Task):
    def __init__(self, config):
        model = SemanticSegmentation(num_classes=2)
        super().__init__(
            model=model,
        )

segmentor = SegmentationTask({})
```

### Expected behavior

Expect model to be able to be a torch lightning module

### Environment

 - PyTorch Version 1.9:
 - OS Windows
 - How you installed PyTorch: pip
 - Build command you used (if compiling from source): 
 - Python version: 3.8
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information:

### Additional context

The culprit is 

https://github.com/PyTorchLightning/lightning-flash/blob/ddd942d3dfe3884a97a855446410166c3c9f16d9/flash/core/model.py#L165-L167

`__setattr__` expects `self._children` to exist but it isn't set until the bottom of the constructor.

**Comment by ethanwharris** [comment]
Hi @dlangerm thanks for reporting this! It looks like it would be safer if we just initialize `_children` in the setattr if it isn't there already, that way it won't depend on the order. Would you be interested in making a PR to fix this?

**Comment by dlangerm** [comment]
@ethanwharris  Unfortunately, in my current role, I don't have a ton of time. If I get some free time today I'll put one together.

**Comment by pietrolesci** [comment]
@ethanwharris this seems to work for me now (I'm on master). For completeness, reporting the `__setattr__` bit below

https://github.com/PyTorchLightning/lightning-flash/blob/eaa0e96bd1184e7a9a5d5badaa50776bd9913f7b/flash/core/model.py#L76-L78

Maybe close this issue?
