### ISSUE TITLE
Create a conda-forge package for lightning-flash

### ISSUE THREAD

**Issue by weiji14** [PyTorchLightning/lightning-flash#659]
### Motivation

Hi there, I'd like to make it easier for users to install `lightning-flash` using the [`conda`](https://docs.conda.io/en/latest/) package manager! I noticed that only `pip install` is possible for lightning-flash v0.4.0 according to https://lightning-flash.readthedocs.io/en/0.4.0/installation.html, but would love to see a `conda install` option too!

### Pitch

Make `conda install -c conda-forge lighning-flash` work.

### Alternatives

Keep using `pip install` only :slightly_smiling_face:

### Additional context

I'll be following the instructions at https://conda-forge.org/#add_recipe to add a new conda-forge recipe to `lightning-flash`, and will submit a Pull Request to https://github.com/conda-forge/staged-recipes. Before I do so though, I'd like to ask:

1. Who is interested to be a recipe maintainer for `pytorch-lightning` on conda-forge? (usually just involves pushing a button when a new version is released, as most things are automated)
2. Are there any complicated dependency issues I should be aware of? I'll just start with the base `lightning-flash` package for now, and maybe do `lightning-flash[all]` later.

**Comment by LoopGlitch26** [comment]
I'm interested to contribute and work on this issue @weiji14 @aniketmaurya

**Comment by weiji14** [comment]
Hi @LoopGlitch26, thanks for your interest! I've opened up a PR already at https://github.com/conda-forge/staged-recipes/pull/15917 to add `lightning-flash` to conda-forge. Once that is merged though, I suppose we'll need to update the installation documentation, would you like to open a PR to update [installation.md](https://github.com/PyTorchLightning/lightning-flash/blob/0.4.0/docs/source/installation.md) with the `conda` install option?

**Comment by weiji14** [comment]
Ok, `lightning-flash` is now available at https://anaconda.org/conda-forge/lightning-flash! However, this is just the base installation (i.e. what you get from `pip install lightning-flash`). There are a few more dependencies that need to be on conda-forge in order to run image/audio tasks. I'll focus on `lightning-flash[image]` since I'm mostly interested in computer vision :sunglasses:

Dependency list from https://github.com/PyTorchLightning/lightning-flash/blob/0.4.0/requirements/datatype_image.txt, :ballot_box_with_check: means available on conda-forge

- [ ] pystiche (>=0.7.2 required)
- [x] [pycocotools](https://anaconda.org/conda-forge/pycocotools) 2.0.2
- [ ] lightning-bolts (>=0.3.3 required, xref request at https://github.com/PyTorchLightning/lightning-bolts/issues/364)
- [x] [kornia](https://anaconda.org/conda-forge/kornia) 0.5.8
- [x] [Pillow](https://anaconda.org/conda-forge/pillow) 8.3.1
- [ ] fiftyone
- [x] [timm](https://anaconda.org/conda-forge/timm) 0.4.12

There are more dependencies on PytorchLightning's master branch, but let's take it one step at a time :grin:

https://github.com/PyTorchLightning/lightning-flash/blob/15bc77891856e06a111f8d410832a376d96d07b7/requirements/datatype_image.txt#L1-L10

Alternatively, the requirements could be relaxed somewhat (i.e. made optional) by modifying https://github.com/PyTorchLightning/lightning-flash/blob/2ec52e633bb3679f50dd7e30526885a4547e1851/flash/core/utilities/imports.py#L93-L102 otherwise people will get hit with an error like `ModuleNotFoundError: Required dependencies not available. Please run: pip install 'lightning-flash[image]`
