### ISSUE TITLE
Keep PL version in sync, push PL 1.4.3 hotfix

### ISSUE THREAD

**Issue by twsl** [PyTorchLightning/lightning-flash#692]
### Motivation

I like to keep my dependencies up to date and the current version 1.4.3 of PL changed/broke a few things. One [fix](https://github.com/PyTorchLightning/lightning-flash/blob/master/flash/core/data/data_pipeline.py#L338) has already been implemented and would solve my problem, but has not yet been pushed.

### Pitch

Push the current changes asap, so the latest version of PL always works with the latest version of flash.

### Alternatives

I do not know your release plan, maybe you have something different in mind or were already planning to do so today.

### Additional context

This is just a heads up, keep up the good work.

**Comment by ethanwharris** [comment]
Hi @twsl thanks for your question! As flash is quite young we don't really have a release schedule yet, but we're looking in to starting one soon! Regarding the hotfix, I've just made a pre-release for 0.5.0, so you should now (or maybe in 20 minutes or so once the release is on PyPi) be able to install with the `--upgrade` and `--pre` flags to get the fixes and test out the upcoming features.

Hope that helps :smiley:
