### ISSUE TITLE
timm models not passed the correct image size

### ISSUE THREAD

**Issue by dlangerm** [PyTorchLightning/lightning-flash#712]
## 🐛 Bug

Flash describes the `timm` models as being supported. Most work out of the box, but specifically, the vision transformers that expect a certain input size, I am plagued with errors such as the following

```
envs\dl\lib\site-packages\timm\models\layers\patch_embed.py", line 33, in forward
    assert H == self.img_size[0] and W == self.img_size[1], \
AssertionError: Input image size (384*384) doesn't match model (224*224).
```

#### Code sample
```python
datamodule = ImageClassificationData.from_folders(
    train_folder="somedata/train/",
    val_folder="somedata/val/",
    test_folder="somedata/test/",
)


model = ImageClassifier(
    backbone="swin_base_patch4_window12_384_in22k",
    optimizer=torch.optim.AdamW,
    learning_rate=1e-4,
    num_classes=datamodule.num_classes,
    metrics=MetricCollection(
        Accuracy(average='macro', num_classes=datamodule.num_classes), 
        F1(average='macro', num_classes=datamodule.num_classes), 
        Precision(average='macro', num_classes=datamodule.num_classes), 
        Recall(average='macro', num_classes=datamodule.num_classes)
    ),
)

trainer = Trainer(gpus=-1, max_epochs=15)

# 6. Train the model
trainer.finetune(model, datamodule=datamodule,
                 strategy=FreezeUnfreeze(unfreeze_epoch=10))
```

### Expected behavior

Seems to me that the input sizes are automatically being adjusted to 196 through some kind of logic, (my images are non-square). But the logic is incorrect for these types of models.

### Environment

 - PyTorch Version (e.g., 1.0): 1.9
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): cconda
 - Python version: 3.9

### Additional context

Seems like this only happens with transformer models from timm.

**Comment by tchaton** [comment]
Hey there,

You need to pass image_size=(224, 224) within your datamodule

**Comment by dlangerm** [comment]
@tchaton Well yes I realize that would fix the problem, but is this documented somewhere? The default behavior seems to be to downsize my images automatically depending on the backbone, but the behavior is inconsistent. Some models cause my images to be downsampled to 196x196, whereas others are downsampled to 244x244. Clearly this downsampling is coming from somewhere as I am not passing any size into the datamodule.
