### ISSUE TITLE
How can I install flash lightning audio and image classification package from source?

### ISSUE THREAD

**Issue by aykutcayir34** [PyTorchLightning/lightning-flash#733]
Hello guys!
I would like to install flash-lightning for image and audio classification from source file. How can I do this?

**Comment by ethanwharris** [comment]
Hi @aykutcayir34 thanks for the question! You should be able to use:
```
pip install 'git+https://github.com/PyTorchLightning/lightning-flash.git#egg=lightning-flash[image,audio]'
```

Hope that helps :smiley:

**Comment by aykutcayir34** [comment]
It works! Thank you very much 👍
