### ISSUE TITLE
Add sample visualization option to the DataModule API

### ISSUE THREAD

**Issue by aribornstein** [PyTorchLightning/lightning-flash#74]
## 🚀 Feature
It would be great to have the ability to sample image, text, tabular and audio samples from the flash datamodule.

### Motivation

In ImageClassificationData, TextClassificationData, TabularClassificationData etc it would be great to have an overridable .visualize() method that plots or visualizes a sample of data.

### Pitch
datamodule = ImageClassificationData.from_folders(
    train_folder="data/hymenoptera_data/train/",
    valid_folder="data/hymenoptera_data/val/",
    test_folder="data/hymenoptera_data/test/",
) 

datamodule.visualize(train, num_samples=6)

[ 1,  2, 3,
 4, 5, 6]

### Alternatives

Open to other ideas.

**Comment by t-vi** [comment]
Ideally, this could be either before or after augmentation / pipeline collation.

**Comment by edgarriba** [comment]
merged #228
