### ISSUE TITLE
Add Image-to-Image translation Task.

### ISSUE THREAD

**Issue by Atharva-Phatak** [PyTorchLightning/lightning-flash#755]
## 🚀 Feature

Flash is amazing and is easy to use. Since there are no GAN-Tasks per se and this would be very broad in nature to do. I was wondering if we could integrate image-to-image translations task using GAN, more specifically - [Cycle-GANs](https://arxiv.org/pdf/1703.10593.pdf) or [Pix2Pix](https://arxiv.org/abs/1611.07004)

### Motivation

To be honest, I am a fan of manga which are always B/W in color it would be nice to have a few liner application to convert B/W images to Colored ones. This can be accomplished using Image-Image translation. 
Here is an example of [manga-colorizer](https://github.com/Atharva-Phatak/Manga-Colorizer/tree/main)

### Pitch

What I want is an integration of image-to-image translation task in Flash with either one of the algorithm running on the backend. I want it to be integrated into seamless API design of Flash.

**Comment by tchaton** [comment]
Dear @Atharva-Phatak,

Thanks for your interest within Lightning Flash.

This is definitely an interesting task, but we integrate only libraries which could be a good backend.
We focus on libraries providing multiple implemented models for the users as Flash aims at becoming an AI Factory.
I have been looking for well implemented libraries for image-2-image translation, but couldn't find any good library.
If you do find one, feel free to make a contribution to the library.

Best,
T.C
