### ISSUE TITLE
Add TextEmbedder Task

### ISSUE THREAD

**Issue by SeanNaren** [PyTorchLightning/lightning-flash#760]
## 🚀 Feature
Using https://github.com/UKPLab/sentence-transformers create a Flash Task for embedding sentences. Sentence Transformers also supports fine-tuning the model onto your own set of data, to improve semantic embedding representations.

### Motivation

It's common to require text search, and sentence-transformers provides great results + an API to fine-tune/predict to get sentence representations out. It could also be paired with [FAISS](https://github.com/facebookresearch/faiss) really simply to provide fast/accurate search results across large datasets.

**Comment by abhijithneilabraham** [comment]
@SeanNaren can I take this up?

**Comment by SeanNaren** [comment]
hey @abhijithneilabraham absolutely! please do :) more than happy to assist if you need help!

**Comment by abhijithneilabraham** [comment]
How do you propose I do this? Open a new module  named `embeddings` inside https://github.com/PyTorchLightning/lightning-flash/tree/master/flash/text and return sentence embeddings?

**Comment by SeanNaren** [comment]
Yep exactly! It would also be possible to fine-tune the model as well on new data, which would be awesome
