### ISSUE TITLE
Output dictionary keys hardcoded in model.py should be in DefaultDataKeys

### ISSUE THREAD

**Issue by dlangerm** [PyTorchLightning/lightning-flash#764]
https://github.com/PyTorchLightning/lightning-flash/blob/143112d01542083214d8d6b1bfba54688ac9cf3e/flash/core/model.py#L353-L355

It seems to me that hardcoding "loss" "y_hat" and "y" in here isn't the best practice and encourages everyone who needs those values in callbacks to either hardcode or store the key values in their own variables. For whatever reason, if the keys were to change, custom callbacks would break easily. 

I propose moving the output keys into the `DefaultDataKeys` for this use case. Naming them something with a prefix so as not to be confused with other input data keys. Alternatively, make a different enum class for these to go in and be used.

**Comment by ethanwharris** [comment]
@dlangerm Thanks for the suggestion! Definitely good to get rid of those magic strings. I think either of your proposed solutions would be fine. Perhaps a new enum is best as it could reside in the same file as the strings for readability. Would you be interested in making a PR to do that?

Thanks :smiley:

**Comment by dlangerm** [comment]
@ethanwharris  https://github.com/PyTorchLightning/lightning-flash/pull/765
