### ISSUE TITLE
Dependency version conflicts on Kaggle Notebooks

### ISSUE THREAD

**Issue by mabu-dev** [PyTorchLightning/lightning-flash#77]
## 🐛 Bug

In Kaggle Notebooks, there's dependency warnings during installation but it succeeds, when trying to `import flash` an error is thrown complaining about the version of `tokenizers`

### To Reproduce

1. Create a Kaggle Notebook with GPU accelerator
2. Run `!pip install lightning-flash` 
3. Try importing flash with `import flash`
4. See error: 
```
VersionConflict: tokenizers==0.9.4 is required for a normal functioning of this module, but found tokenizers==0.9.3.
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git master
```

#### Code sample

```
!pip install lightning-flash 
import flash
```

### Expected behavior
![image](https://user-images.githubusercontent.com/22409996/107147807-af0f8300-6958-11eb-9782-9148bca49864.png)

### Environment
 - Kaggle Notebooks
 - GPU Compute

**Comment by akihironitta** [comment]
@mabu-dev Hi, thank you for reporting the issue. I think this is not an issue from `flash` as we don't have any required version for `tokenizers`. You should be able to `import flash` by upgrading the version of `tokenizers` from 0.9.3 to 0.9.4 as indicated in the error message.
