### ISSUE TITLE
Classification with only numerical features

### ISSUE THREAD

**Issue by zippeurfou** [PyTorchLightning/lightning-flash#772]
## 🚀 Feature
To do classification you might sometimes only have numerical fields. Today the closest you can do is with tabular classification. However it does expect to have categorical fields.

```
~/conda/lib/python3.8/site-packages/numpy/core/shape_base.py in stack(arrays, axis, out)
    421     arrays = [asanyarray(arr) for arr in arrays]
    422     if not arrays:
--> 423         raise ValueError('need at least one array to stack')
    424
    425     shapes = {arr.shape for arr in arrays}

ValueError: need at least one array to stack
```

**Comment by noobyogi0010** [comment]
@zippeurfou I would like to work on implementing this feature. Can I take it up?

**Comment by tchaton** [comment]
Dear @noobyogi0010,

Yes, please do :) 

Best,
T.C
