### ISSUE TITLE
[RFC] Hosting and Serving Models with Flash

### ISSUE THREAD

**Issue by oke-aditya** [PyTorchLightning/lightning-flash#79]
# Flash Serve !!

## Motivation

Most people want to also try a demo of models as REST API or say some sort of inference API.
E.g. HuggingFace API, people can have a run out of the box.

This also demonstrates some of out of box models which are associated with Tasks.
Sometimes people need a simple service, either for hobbies or for say small tasks.
Maybe someone is doing a small project and needs an API out of the box that does Object Detection, Segmentation etc
Alternatives are with Google Cloud AI service or say Azure AI service, etc. but they are paid and too difficult to work with.
Many such use cases are possible!

## Pitch

Serve Flash models with Torchserve. Torchserve works out of the box with all torchvision models (we use them in Flash)
Torchserve makes it easy to create hosted API, we don't have to worry about protocols underlying inference logics.
Well supported and scalable. Also, it is quite fast.

### Why torchserve ?

Well writing own protocols and simple REST API is sometimes not enough, a scalable approach that works really well is needed.
Torchserve directly works on all OSes, support to cloud platforms too. Written in Java so really fast.
We don't have to worry about scalability, and end users don't have to worry about models !

## Additional Context

Well there are various ways of creating RESTful service, say FastAPI, Flask, Django, Node.js, what not. But If we use Torchserve we don't have to worry about multi-processing over CPU, GPU, supporting all OSes, scaling to say Kubernetes, etc.

Thanks a lot to @aniketmaurya for sparking these over slack discussion !

P.S. I'm highly willing to contribute to this. Let me know !

**Comment by aniketmaurya** [comment]
_Reposting my comment from slack:_
> Thanks for posting this @oke-aditya 
As you mentioned Torchserve is a great tool for people who would like to productionize their model or even for a simple demo.
I am not sure about Flash Serving but a general PL Serving may help a wider audience I guess.

PS. It is a much-needed tool and I would love to contribute to this.

**Comment by t-vi** [comment]
> Well there are various ways of creating RESTful service, say FastAPI, Flask, Django, Node.js, what not. But If we use Torchserve we don't have to worry about multi-processing over CPU, GPU, supporting all OSes, scaling to say Kubernetes, etc.

When I looked around in the context of [ch 15 of our book](https://github.com/deep-learning-with-pytorch/dlwpt-code/blob/master/p3ch15/request_batching_jit_server.py), it seemed that the key questions with using Python (I used sanic over flask because it seemed like simple to use but async) were 1) is it safe (when it calls into extensions, e.g. for image processing)? 2) can you avoid copying as much as possible. Note that TorchScript pretty much solves the "GIL topic" for the model parts.
For the " multi-processing over CPU, GPU, supporting all OSes, scaling" bits, it might be even more natural to look at lightning over TorchServe for us here, so it might be good to have a comparison what is missing that lightning cannot provide here. Personally, I am not a huge fan of installing Java in more places than I have to.

**Comment by oke-aditya** [comment]
True that it would be possible with Python and there are ways to overcome with GIL.
But there are to of issues that could occur while we implement. Working with scripted models, metrics management, logging. Supporting more than 1 model serving parallel, distributing models over CPU Cores.

Installing Java is not needed for users ! 

All they would need to do is

```
curl server_ip/predictions/densenet161 -T kitten_small.jpg
```

or send a POST Request.

Torchserve is very very well maintained and engineered. There was really a long discussion in PyTorch about this. Refer[ here](https://github.com/pytorch/pytorch/issues/27610)

Let me know more thoughts. Maybe I should elaborate on idea ?

**Comment by aniketmaurya** [comment]
> Torchserve is very very well maintained and engineered. There was really a long discussion in PyTorch about this. Refer here

Torchserve allows serving by versioning the models and also provides both gRPC and REST API support.
It is well maintained and expected to be maintained in future too. We can follow the main core value of Lightning `One less thing to remember` and provide users with an API which they can use without any extra effort.
