### ISSUE TITLE
Jina integration

### ISSUE THREAD

**Issue by bwanglzu** [PyTorchLightning/lightning-flash#795]
Dear @tchaton ,

Sorry for the late reply for [your request](https://github.com/jina-ai/jina/issues/3387#issue-993766221), last week a lot of our engineers went for vacation :) 
We're definitely interested in this! If possible I could collaborate with you to create a Jina executor over lighting-flash.

Best

Bo @jina-ai

**Comment by tchaton** [comment]
Dear @bwanglzu,

Great to hear ! 

I wondered if you would be willing to get started on you side ? I am not familiar with Jina yet.
It would help me to get onboarded faster.

Best,
T.C

**Comment by bwanglzu** [comment]
Hi @tchaton ,

Yea sure, I'll create a open ticket and demonstrate steps in the ticket, and start implementation next week. But before that I'll try to get familiar with lightning-flash. We keep in touch. Do you have a community slack channel or something like that for easier communication?

Best

Bo

**Comment by hanxiao** [comment]
hi, @tchaton , let me pair with me on this ticket, replied you on linkedin
