### ISSUE TITLE
VideoClassificationData.from_files() does not work

### ISSUE THREAD

**Issue by Darktex** [PyTorchLightning/lightning-flash#798]
## 🐛 Bug
`VideoClassificationData.from_files()` does not work. `VideoClassificationData` objects can only be constructed using the `from_folders()` classmethod - which unfortunately doesn't work for multilabel tasks :)

### To Reproduce
I wrote a Colab notebook to reproduce this in a self-contained environment: https://colab.research.google.com/drive/1X7UvZDndCc0dzcUZ_fGdmQz0ZMTTsj_U?usp=sharing

#### Code sample
See link to colab above

### Expected behavior
A `VideoClassificationData` object should be constructed from a list of paths and their labels

**Comment by tchaton** [comment]
Dear @Darktex,

It should be too hard to support. Would you be interested to give it a try and open a PR ? I would help you if needed 

Best,
T.C

**Comment by Darktex** [comment]
Of course! I tried for a bit on my own, but I wasn't able to track down the root cause - lots of delegation going on :(

I think I'd need some pointers to unblock

**Comment by Darktex** [comment]
See #823
