### ISSUE TITLE
Petastorm Support

### ISSUE THREAD

**Issue by dlangerm** [PyTorchLightning/lightning-flash#802]
## 🚀 Feature
It'd be pretty cool to have [Petastorm](https://github.com/uber/petastorm) integration. Personally I don't use it, but I think I would if there were built-in support for the format. 

### Motivation

Large datasets are unwieldy at the best of times, and the petastorm format was developed to encapsulate large datasets while allowing high-efficiency reads and writes. It also works with smaller datasets and can enable transparent in-memory data loading for high-performance training needs. 

### Pitch

Enable loading data from datasets in the .petastorm format. This likely requires abstracting the dataloader to use the petastorm loader as an optional extension. Not much else would have to change AFAIK. 

### Alternatives

I believe this could be enabled by any user out of the box by overriding the lightning module method for creating dataloaders, but this is clunky to have to do for every project and is error-prone since the dataloader is such a low-level access object and should ideally be left alone because it's parameterized by a lot of other things.

**Comment by tchaton** [comment]
Sounds like a good idea. Do you want to give it a go ?

**Comment by tchaton** [comment]
I guess webdataset could also be used too

**Comment by chongxiaoc** [comment]
```Enable loading data from datasets in the .petastorm format. This likely requires abstracting the dataloader to use the petastorm loader as an optional extension. Not much else would have to change AFAIK.```

@dlangerm  Petastorm uses Parquet as file format. Can parquet files be served as input for any usage in `lightning-flash`?

Also, I did some work of integrating Petastorm with Lightning trainer in Horoovd, creating a new `datamodule` with Petastorm is a preferred way to go. Here is the [integration](https://github.com/horovod/horovod/blob/master/horovod/spark/lightning/datamodule.py) for Petastorm and Lightning I did for Horovod.

**Comment by dlangerm** [comment]
@chongxiaoc I'm sure it could be used for all kinds of things if support is added (perhaps adding a converter to go between petastorm, a binary format, and a loose file dataset, but that feels out of scope for flash). 

Personally I was looking into it because I wanted better performance from a dataset that I knew could fit into memory but has mixed tabular and image data.

**Comment by nilesh-patil** [comment]
Hi

Any solution to make `lightning-flash` + `Petastorm` work together ?
