### ISSUE TITLE
Errors Following Installation Instructions Due to Dependency Conflicts With Imageing Libraries 

### ISSUE THREAD

**Issue by alexheat** [PyTorchLightning/lightning-flash#803]
## 🐛 Bug

I am new to PyTorch Lightning Flash and was unable to install lightning-flash using the directions here https://lightning-flash.readthedocs.io/en/latest/installation.html. I was only able to get it working due to the great help from Thomas Chaton on the Slack support group. I am documenting the issues and workarounds so that they can be found by others and fixed so that other noobs like me can more easily get started with PyTorch. 

My issues may be specific to the Image related tasks such as https://lightning-flash.readthedocs.io/en/latest/reference/object_detection.html. 

### To Reproduce

1.  Install Pytorch using one of the documented  methods at https://lightning-flash.readthedocs.io/en/latest/installation.html. For example `pip install 'lightning-flash[image]'
2. Run code sample at https://lightning-flash.readthedocs.io/en/latest/reference/object_detection.html 

The errors start as soon you try to import the libraries. An example error is 

`ImportError: /usr/local/lib/python3.7/dist-packages/torchtext/_torchtext.so: undefined symbol: _ZN2at6detail10noopDeleteEPv`

There are issues with torch text, icevision, and fastai libraries. 

### Expected behavior

The samples should install and run without modification. 

### Environment

- This is repro in fresh Google collab notebook. 

### Additional context

With Thomas Chaton's help I have created a notebook with workarounds that will get the code samples working. 

https://gist.github.com/alexheat/31538153e365ecc996fd45e6093c1e68

The workarounds are to apply specific builds of dependencies and apply a bug fig to the icevision library. 

```
!pip install torch==1.8.1+cu102 -f https://download.pytorch.org/whl/torch_stable.html
!pip install icevision #==0.9.0a1
!pip install effdet 
!pip install lightning-flash[image]
!pip install git+https://github.com/PyTorchLightning/lightning-flash.git
!pip install torchtext==0.9.1
!pip uninstall fastai -y
#There is a bug in the latest release of icevision. Manually apply the fix.
!curl https://raw.githubusercontent.com/airctic/icevision/944b47c5694243ba3f3c8c11a6ef56f05fb111eb/icevision/core/record_components.py --output /usr/local/lib/python3.7/dist-packages/icevision/core/record_components.py
#Restart the kernel
```
Hopefully you can update the core setup so the workarounds are not needed. Or at least make these workarounds known to others.

**Comment by aribornstein** [comment]
I was able to resolve this by using this version of torchtext. Agree that this shouldn't be dependency for image tasks.

!pip install torchtext==0.9.1

**Comment by ethanwharris** [comment]
Closing this issue in favour of #949 - the workaround here is to install with:
```
pip uninstall -y torchtext fastai
pip install lightning-flash[image] icevision
```

Please feel free to reopen if needed
