### ISSUE TITLE
dict update problem

### ISSUE THREAD

**Issue by zhaoedf** [PyTorchLightning/lightning-flash#814]
### To Reproduce

```python
import torch
from torch.utils.data import Dataset, random_split

from pytorch_lightning import seed_everything

import flash
from flash.core.classification import Labels
from flash.core.data.utils import download_data
from flash.image import ImageClassificationData, ImageClassifier

from torchvision.datasets import CIFAR10


seed_everything(42)

train = CIFAR10(root='/data/Public/Datasets/', train=True)
test = CIFAR10(root='/data/Public/Datasets/', train=False)


datamodule = ImageClassificationData(
    train_dataset=train,
    test_dataset=test,
    val_split = 0.1,
    batch_size = 32,
    num_workers = 8
)


model = ImageClassifier(
    backbone="resnet18",
    pretrained=True,
    num_classes=256
)

trainer = flash.Trainer(max_epochs=1, gpus=1)

trainer.fit(model, datamodule=datamodule)

trainer.save_checkpoint("image_classification_model.pt")
```

1. run above code

![image](https://user-images.githubusercontent.com/48846150/135265835-7a1b79a2-47f8-4fab-a1a0-d4664e8d6ade.png)

### Environment

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by zhaoedf** [comment]
i change multiple dataset, but this problem still exists.

**Comment by kingyiusuen** [comment]
I think you just need to change

```
datamodule = ImageClassificationData(
```

to

```
datamodule = ImageClassificationData.from_datasets(
```

**Comment by SeanNaren** [comment]
I can confirm once modifying the code to what @kingyiusuen after the dataset has been downloaded, this works! Feel free to open this issue again if the issue persists!
