### ISSUE TITLE
Error on TranslationTask.load_from_checkpoint 

### ISSUE THREAD

**Issue by mabu-dev** [PyTorchLightning/lightning-flash#819]
## 🐛 Bug

When running:
`model = TranslationTask.load_from_checkpoint("https://flash-weights.s3.amazonaws.com/translation_model_en_ro.pt")`

I get:
`AttributeError: 'Seq2SeqCSVDataSource' object has no attribute 'backbone_kwargs'`

### To Reproduce

```
from flash.text import TranslationTask
model = TranslationTask.load_from_checkpoint("https://flash-weights.s3.amazonaws.com/translation_model_en_ro.pt")
```

### Environment

GoogleColab

### Additional context
![image](https://user-images.githubusercontent.com/22409996/135499477-de638917-945e-43ce-85e6-5202e9208fe7.png)

**Comment by ethanwharris** [comment]
Closing as this is addressed by #931 - you would now have a pretrained weights path for the specific version of flash you are using. E.g. in 0.5.1 it is:
```
https://flash-weights.s3.amazonaws.com/0.5.1/translation_model_en_ro.pt
```
Hope that helps :smiley:
