### ISSUE TITLE
Image classification Finetuning tutorial.

### ISSUE THREAD

**Issue by t-vi** [PyTorchLightning/lightning-flash#83]
## 📚 Documentation

Having pictures and text with the predictions would be nice. Probably there is some lib that already does that, but so this was the first thing I did here:

![image](https://user-images.githubusercontent.com/20787943/107218622-2522f100-6a10-11eb-8e50-d0bd6d42217f.png)

Also, if you look at the tutorial, finetuning and then loading the pre-finetuned model from s3 doesn't make a whole lot of sense to me. I would suggest to load from the just created file and comment out the line that loads from s3.

Finally, the s3 weight file name seems awfully generic for a bee vs. ant model.

**Comment by kaushikb11** [comment]
@t-vi What do you think of [IpyPlot](https://github.com/karolzak/ipyplot) for visualization?

**Comment by kaushikb11** [comment]
Also, I was thinking we should add functionalities for Error Analysis on the predictions for the users.

**Comment by t-vi** [comment]
@kaushikb11 I don't know it, so I have to defer to other peoples expertise. One of the key things (in addition to quality) would be if it adds dependencies - of which Flash has too many and too specific ones IMHO.

Actually for the visualization, things are a bit more subtle than the example above suggests: Ideally, I could also show the preprocessed images in a straightforward way, so our visualization might make use of the data pipeline.

**Comment by edenlightning** [comment]
Thanks for the issue! Would something like https://github.com/pytorchlightning/lightning-flash/issues/74 work?

**Comment by t-vi** [comment]
I think yes.
