### ISSUE TITLE
ImageClassifier Predict Label

### ISSUE THREAD

**Issue by aribornstein** [PyTorchLightning/lightning-flash#84]
## 🚀 Feature
Prediction Currently Returns the class index based on the folder position in train. It would be great to be able to able to see the targets. 

### Motivation
It's hard to interpret class id numbers when you have more than a few classes.
model.predict(["cat.png"], target=true)
output -> 1

What does one mean?

### Pitch

model.predict(["cat.png"], target=true)
output ->cat
### Alternatives

Open to discussion

**Comment by ibraheemmmoosa** [comment]
Another alternative can be to have an easy API to convert between ID and class label. The ID is important if you want your output to be numerical.

**Comment by aribornstein** [comment]
Adding to this,a way to get the prediction class distribution.

**Comment by ethanwharris** [comment]
Fixed by #229 - can now use `model.serializer = Labels()` or `model.serializer = Probabilities()`, for other options see [the predictions docs](https://lightning-flash.readthedocs.io/en/latest/general/predictions.html#serializing-predictions).
