### ISSUE TITLE
The test step should not use the same metrics objects as validation

### ISSUE THREAD

**Issue by carmocca** [PyTorchLightning/lightning-flash#843]
## 🐛 Bug

https://github.com/PyTorchLightning/lightning-flash/blob/eb1fcd3925ee297d08704d48c5fc57624665ad96/flash/core/model.py#L424

**Comment by ethanwharris** [comment]
We do a deepcopy of the metrics object here: https://github.com/PyTorchLightning/lightning-flash/blob/eb1fcd3925ee297d08704d48c5fc57624665ad96/flash/core/model.py#L335 - which seems to be sufficient to get the correct results. Simple test for correctness here (although this could be expanded): https://github.com/PyTorchLightning/lightning-flash/blob/eb1fcd3925ee297d08704d48c5fc57624665ad96/tests/core/test_model.py#L345
