### ISSUE TITLE
Best way to change how data is read in datamodule?

### ISSUE THREAD

**Issue by bartonp2** [PyTorchLightning/lightning-flash#866]
#### What is your question?
I have a semantic segmentation task but need to read the input images with `tifffile.imread()` rather than the standard PIL reader.  The change needed only concerns the following two lines within the `load_sample()` function of the `SemanticSegmentationPathsDataSource() `class:

        # load images directly to torch tensors
        img: torch.Tensor = FT.to_tensor(default_loader(img_path))  # CxHxW
        img_labels: torch.Tensor = torchvision.io.read_image(img_labels_path)  # CxHxW

which I would like to change to:

        # load images directly to torch tensors
        img: torch.Tensor = FT.to_tensor(tifffile.imread(img_path))  # CxHxW
        img_labels: torch.Tensor = torch.from_numpy(tifffile.imread(img_labels_path).transpose((2, 0, 1))).contiguous()  # CxHxW

 My current approach is to create a child class of `SemanticSegmentationPathsDataSource()` in which I overload the ` load_sample()` function with the change mentioned above. I further have to create a child class of `SemanticSegmentationPreprocess()` in which I overload the `__init__()` function to recognise my datasource.

To create my segmentation datamodule I then call `SemanticSegmentationData.from_data_source('my_new_source', preprocess=[my new preprocess object], ...)` . This procedure seems to work for training although the prediction phase appears to require further modifications of datasources again.

So my question is: Is this the best way to make the required change or is there another cleaner way? 

#### What's your environment?

 - OS: Ubuntu18
 - Packaging conda
 - Version 0.5.0

**Comment by bartonp2** [comment]
Actually, a similar problem has come up again. This time I want to change the Object Detection Task to read raw .CR2 files instead of jpg or similar. I cannot figure out an easy way to do this and find myself diving deep into the code and icevision data sources. Is there an example somewhere of how to do this more easily?

**Comment by ethanwharris** [comment]
@bartonp2 Thanks for the question. This is definitely a limitation of our current API but we are in the process of a refactor (see `Data Pipeline V2` labelled issues) which aims to make it much easier to bring custom data to Flash. I will share more on here once the refactor is complete but please also feel free to reach out on the PyTorch Lightning slack if you would like to hear more about it :smiley:

**Comment by bartonp2** [comment]
@ethanwharris Thanks for the prompt answer. Do you have any time frame estimate of when these changes will be ready?

**Comment by bartonp2** [comment]
The new pipeline makes it easier to change how files are read, but for the object detection task this involves diving into the IceVision code. Therefore I post the solution in this specific case, in case anyone else needs to do something similar::

```from flash.image import ObjectDetectionData
from icevision import BaseRecord
from icevision.core.record_components import FilepathRecordComponent
from icevision.parsers.coco_parser import COCOBBoxParser


class CustomFilepathRecordComponent(FilepathRecordComponent):
    """ Overrides _load function to load raw files in addition to normal images"""
    def _load(self):
        # Todo: replace open_img with your custom file reader

        img = open_img(self.filepath, gray=self.gray)
        if self.gray:
            img = img.convert("RGB")
        self.set_img(img)


class CustomCocoParser(COCOBBoxParser):
    """ Edit template record to use custom CustomFilepathRecordComponent"""
    def template_record(self) -> BaseRecord:
        record = super().template_record()
        record.remove_component_by_type(FilepathRecordComponent)
        record.add_component(CustomFilepathRecordComponent())
        return record

ObjectDetectionData.from_icedata(parser=CustomCocoParser)
