### ISSUE TITLE
Locked torchmetrics version

### ISSUE THREAD

**Issue by twsl** [PyTorchLightning/lightning-flash#901]
### To Reproduce

1. Install latest `torchmetrics` via pip (0.6.0)
2. Install latest `lightning-flash` via pip
3. See error, version locked to `<=0.5.0`

### Expected behavior

Install just fine

### Environment

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):-
 - Python version: 3.8
 - CUDA/cuDNN version: -
 - GPU models and configuration:-
 - Any other relevant information:

**Comment by ethanwharris** [comment]
Ah, this should be updated to `torchmetrics!=0.5.1` to avoid a specific bug from that version. @twsl Would you be interested in contributing the fix?
