### ISSUE TITLE
Difficulties Running DINO ImageEmbedder

### ISSUE THREAD

**Issue by jlevy44** [PyTorchLightning/lightning-flash#941]
Hi there! I am having difficulties running the dino training strategy for the ImageEmbedder module. Particularly, it appears the center is not initializing (set to None):
```
config={"momentum": 0.996,
    "student_temp": 0.1,
    "teacher_temp_min": 0.04,
    "teacher_temp_max": 0.07,
    "teacher_temp_warmup_iters": 37500, 
    "crops_for_teacher": [0, 1],
    "ema_center": 0.9,
    "normalize_last_layer": True,
    "output_dim": 65536 }

embedder = ImageEmbedder(
    backbone="vision_transformer",
    training_strategy="dino",
    head="dino_head",
    pretraining_transform="dino_transform",
    training_strategy_kwargs=config
)

trainer = flash.Trainer(max_epochs=16, gpus=[0])
trainer.fit(embedder, datamodule=data_module)
```
Which leads to this error:
```
~/.local/lib/python3.7/site-packages/vissl/losses/dino_loss.py in forward(self, output, *args, **kwargs)
    101         # teacher centering and sharpening
    102         teacher_out = F.softmax(
--> 103             (self.teacher_output - self.center) / self.teacher_temp, dim=-1
    104         )
    105         teacher_out = teacher_out.detach().chunk(

~/.local/lib/python3.7/site-packages/torch/tensor.py in __rsub__(self, other)
    526         if has_torch_function_variadic(self, other):
    527             return handle_torch_function(Tensor.__rsub__, (self, other), self, other)
--> 528         return _C._VariableFunctions.rsub(self, other)
    529 
    530     def __rdiv__(self, other):

TypeError: rsub() received an invalid combination of arguments - got (Tensor, NoneType), but expected one of:
 * (Tensor input, Tensor other, *, Number alpha)
 * (Tensor input, Number other, Number alpha)
```
Potentially, I am not following the correct set up instructions? #893

Thanks!

**Comment by jlevy44** [comment]
Actually I have it the other way around. I believe the teacher_output and teacher_temp is None.

**Comment by jlevy44** [comment]
I have been modifying the dino_loss function to test various components

**Comment by jlevy44** [comment]
https://github.com/facebookresearch/vissl/blob/116ac703a360a8783266960f722d00680b42286b/vissl/hooks/dino_hooks.py#L136

**Comment by jlevy44** [comment]
https://github.com/facebookresearch/vissl/blob/main/vissl/hooks/dino_hooks.py

**Comment by jlevy44** [comment]
I would suspect that the teacher network is not being initialized when the sanity_check is being run. As a test, I can move past this step by overloading the sanity_check:
```
class Trainer2(flash.Trainer):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
    def _run_sanity_check(self, pl_mod):
        pass
```

**Comment by jlevy44** [comment]
Also the registered buffer does not appear to work: 
https://github.com/facebookresearch/vissl/blob/116ac703a360a8783266960f722d00680b42286b/vissl/losses/dino_loss.py#L34
Replaced with:
```
self.center=torch.zeros(1, loss_config["output_dim"])
if torch.cuda.is_available():self.center=self.center.cuda()
```
Appears to run now.

**Comment by tchaton** [comment]
@ananyahjha93

**Comment by ananyahjha93** [comment]
@jlevy44 on it, let me take a look and get back

**Comment by ananyahjha93** [comment]
@jlevy44 hey, can you post the modified DINO loss you mentioned. I am not able to replicate the error you have mentioned here. 

PS: 

is standard DINO loss function working for you without using the ``accelerator='ddp'`` flag? Ideally it shouldn't. I would recommend changing your ``Trainer`` init to:

```
trainer = flash.Trainer(max_epochs=16, gpus=[0], accelerator='ddp')
```

**Comment by jlevy44** [comment]
Thanks! I remember running into issues using ddp but will check and get back to you, re: loss changes.

Even though I did get it to run, the loss does not appear to decrease, but could be related to the changes I made to the loss function (e.g., maybe center doesn't behave as it should).
