### ISSUE TITLE
[text] Extendable Backbones and Dataloaders

### ISSUE THREAD

**Issue by aribornstein** [PyTorchLightning/lightning-flash#95]
## 🚀 Feature
Backbones and Dataloaders are tightly coupled to tasks this makes it hard for example to use a non huggingface model for text classification or flair embeddings for featurization. 

### Motivation

In order to prevent duplicate tasks for different backbone libraries Flash needs an extendable way of adding backbones to a task.

**Comment by carmocca** [comment]
@aribornstein is this a duplicate of https://github.com/PyTorchLightning/lightning-flash/issues/167 ?

**Comment by edgarriba** [comment]
@aribornstein backbones api is already merged. Can we close this ?
