### ISSUE TITLE
Integrate backbones from PyTorch Tabular for tabular classification and regression tasks

### ISSUE THREAD

**Issue by ethanwharris** [PyTorchLightning/lightning-flash#950]
## 🚀 Feature

Use the models from here: https://github.com/manujosephv/pytorch_tabular

TabNet would work as currently but also have the others as options

**Comment by Actis92** [comment]
Hi @ethanwharris in the last weeks I have worked on Pytorch-Tabular so if you want I can try to help for the integration

**Comment by ethanwharris** [comment]
Hi @Actis92 That would be great! I'll assign you to the issue. Please reach out if you want to discuss / brainstorm anything. It looks like they have lightning modules for the models so we should be able to make it work with the `flash.core.adapter.Adapter`. You could look at our IceVision and PyTorch Forecasting integrations to see how we did it there :smiley:

**Comment by Actis92** [comment]
Hi @ethanwharris,
sorry for the delay in the answer but I was quite busy. I'm trying to do the integration using the Adapter like pytorch forecasting, let me know if for you is ok that I open the pull request in this way you can start to give a look in order to see if i'm going on the right path

**Comment by ethanwharris** [comment]
Hey @Actis92 Awesome! Thanks for opening the PR, I'll take a look :smiley:
