### ISSUE TITLE
Allow to specify the detection_threshold in the prediction method of ObjectDetector

### ISSUE THREAD

**Issue by Actis92** [PyTorchLightning/lightning-flash#954]
## 🚀 Feature
Allow in the method predict of the ObjectDetector to specify the parameter detection_threshold that is used to filter the bounding box in base of the confidence of the model

### Motivation

In Icevision is possible to specify the detection_threshold that is used to filter the bounding box predicted by the model. If it's not specified the value is set to default at 0.5. Instead using ObjectDetector is not allow to specify this parameter and then the prediction are always filtered using the default threshold

### Pitch

Allow to specify a custom value for the threshold used to filter the bounding boxes

### Additional context

This is a screenshot of the predict method used in Icevision. If you agree that is can be useful to add this functionality I can work on it and open a PR
<img width="409" alt="Schermata 2021-11-12 alle 12 58 43" src="https://user-images.githubusercontent.com/46601193/141463803-da960805-0821-4761-a530-12f2d28819db.png">

**Comment by ethanwharris** [comment]
Hi @Actis92 Yes I think this would be a very welcome addition! Here is the line that calls `predict_from_dl`, you could pass the additional kwarg there (which I think should be a property of the model set on init, maybe with a setter / getter in case people want to change it): https://github.com/PyTorchLightning/lightning-flash/blob/a0c97a39f2083b5344a08d248ccab7e5bfa91df4/flash/core/integrations/icevision/adapter.py#L201

Let me know if you have any issues implementing it :smiley:

**Comment by Actis92** [comment]
Hi @ethanwharris I have done the changes, I think in the same way as you have suggested. I have opened a pull request, so let me know if you think it's ok or must be done in a different way :)
