### ISSUE TITLE
Drop `from_*` methods from base `DataModule` and move out to interfaces

### ISSUE THREAD

**Issue by ethanwharris** [PyTorchLightning/lightning-flash#956]
Make it easier to implement new / custom datamodules and organize / standardize our code base a bit more by adding interfaces that give the base spec. for each `from_*` method.

**Comment by karthikrangasai** [comment]
Hello all,
One thing to note is that some filetype based kwargs can't be sent to the `from_*` methods.

For example, in the `from_csv` method we can't pass `pandas.read_csv` specific keyword arguments like `sep` to enable usage for `tsv` files etc.

Could this be looked into during this refactor ?

**Comment by ethanwharris** [comment]
@karthikrangasai Definitely! Mind opening an issue to track this directly? Just so we don't miss it :smiley:

**Comment by karthikrangasai** [comment]
Sure, I will do it.
