### ISSUE TITLE
`TextClassifier` with `load_from_checkpoint` still downloads data

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/lightning-flash#984]
## 🐛 Bug

When I train a model I want to use it offline, so I save it, but when I load it from the saved model it still pulls the online model
https://github.com/PyTorchLightning/lightning-flash/blob/a0c97a39f2083b5344a08d248ccab7e5bfa91df4/flash/text/classification/model.py#L90

### To Reproduce

https://www.kaggle.com/jirkaborovec/toxic-comments-with-lightning-flash-inference?scriptVersionId=80368862

### Additional context

cc: @rohitgr7 @karthikrangasai

**Comment by rohitgr7** [comment]
I guess this is expected because load_from_checkpoint first initializes the model and then load the checkpoint weights. Can you try attaching the dataset for the model and pass the path to it?
```py
model = TextClassifier.load_from_checkpoint(..., backbone=local_model_pth)
```

**Comment by Borda** [comment]
> I guess this is expected

well, shouldn't the checkpoint also include the architecture so it can be fully restored without any extra data?
me being a naive user: imagine that you saved your checkpoint but don't remember the backbone name which was used as one hyperparameter, then you can't use the checkpoint, anymore?

**Comment by Borda** [comment]
could be a solution: https://stackoverflow.com/a/62288407/4521646
```py
# Saving...
model.model.save_pretrained("./my_named_bert")
trainer.save_checkpoint("text_classification_model.pt")
# Restore...
m2 = TextClassifier.load_from_checkpoint("text_classification_model.pt", backbone="./my_named_bert")
```

**Comment by mrleu** [comment]
hello! I am interested to work on this if this hasn't been worked on!

**Comment by abhijithneilabraham** [comment]
@Borda  Has this been fixed? Can I take this up?

**Comment by mrleu** [comment]
go for it @abhijithneilabraham . first i signed up for this issue before, but turns out i didn't have the bandwidth. thank you!

**Comment by abhijithneilabraham** [comment]
@Borda @rohitgr7  I looked into the issue. The download happens in the first run alone. I suppose this is an essential step, since we need those backbone models and tokenizer which could be used while running further finetuning or prediction steps. The `load_from_checkpoint` just loads a pytorch model, rest of the configuration(model, tokenizer,config files) if not present, is what's getting downloaded.
